{{- $name := "odbc-config" -}}

{{- $dwEnabled := (include "redpoint.DatawarehouseProviders" .) | eq "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{- include "redpoint-rpi.componentLabels" (dict "root" . "name" $name "component" "configmap") | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
data:
  odbc2.ini: |
    [ODBC]
    Trace=no

    [ODBC Data Sources]

    {{- $dw := .Values.databases.datawarehouse | default dict -}}

    {{- with ($dw.bigquery | default dict) }}
    {{- if (.enabled | default false) }}
    {{- range .connections }}
    {{ .name }}=Simba ODBC Driver for Google BigQuery 64-bit
    Description=Simba ODBC Driver for Google BigQuery (64-bit) DSN
    Driver=/app/odbc-lib/bigquery/SimbaODBCDriverforGoogleBigQuery64/lib/libgooglebigqueryodbc_sb64.so
    Catalog={{ .projectId }}
    SQLDialect={{ .sqlDialect }}
    AllowLargeResults={{ .allowLargeResults }}
    LargeResultsDataSetId={{ .largeResultsDataSetId }}
    LargeResultsTempTableExpirationTime={{ .largeResultsTempTableExpirationTime }}
    OAuthMechanism={{ .OAuthMechanism }}
    Email={{ .serviceAccountEmail }}
    KeyFilePath={{ .mountPath }}/{{ .keyName }}
    {{- end }}
    {{- end }}
    {{- end }}

    {{- with ($dw.databricks | default dict) }}
    {{- if (.enabled | default false) }}
    {{- range .connections }}
    {{ .name }}=Simba Apache Spark ODBC Connector
    Driver=/app/odbc-lib/simba/spark/lib/libsparkodbc_sb64.so
    SparkServerType=3
    Host={{ .host }}
    Port={{ .port }}
    Schema={{ .schema }}
    SSL=1
    Min_TLS=1.2 
    ThriftTransport=2
    AuthMech={{ .authMechanism }}
    UID={{ .username }}
    PWD={{ .password }}
    TrustedCerts=/app/odbc-lib/simba/spark/lib/cacerts.pem
    UseSystemTrustStore=0
    HTTPPath={{ .httpPath }}
    {{- end }}
    {{- end }}
    {{- end }}
