{{- $cfg := fromYaml (include "rpi.merged.keycloak" .) -}}
{{- $liveness := fromYaml (include "rpi.merged.livenessProbe" .) -}}
{{- $startup := fromYaml (include "rpi.merged.startupProbe" .) -}}
{{- $ingCfg := fromYaml (include "rpi.merged.ingress" .) -}}
{{- $name := "keycloak" -}}

{{- if .Values.smartActivation.enabled }}
{{- if not .Values.cloudIdentity.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smartactivation.componentLabels" (dict "root" . "name" $name "component" "authservice") | nindent 4 }}
  {{- $annotations := include "rpi.cloudidentity.saAnnotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.smartActivation.enabled }}
{{- if $cfg.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smartactivation.componentLabels" (dict "root" . "name" $name "component" "authservice") | nindent 4 }}
spec:
  minAvailable: {{ $cfg.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
{{- end }}     
{{- end }}  

---
{{- if .Values.smartActivation.enabled }}
{{- if eq $cfg.type "rollout" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-preview
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smartactivation.componentLabels" (dict "root" . "name" $name "component" "authservice") | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ $cfg.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ $name }}
{{- end }}     
{{- end }}  

---
{{- if .Values.smartActivation.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smartactivation.componentLabels" (dict "root" . "name" $name "component" "authservice") | nindent 4 }}
spec:
  ports:
  - name: http
    port: {{ $cfg.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ $name }}

---
{{- if eq $cfg.type "rollout" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- end }}
{{- if eq $cfg.type "deployment" }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  labels:
    {{- include "smartactivation.componentLabels" (dict "root" . "name" $name "component" "authservice") | nindent 4 }}
    app.kubernetes.io/version: {{ .Values.global.deployment.images.tag | quote }}
  annotations:
    {{- with .Values.customAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ $cfg.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  {{- if eq $cfg.type "deployment" }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ $cfg.rollingUpdate.maxUnavailable | default "25%" }}
      maxSurge: {{ $cfg.rollingUpdate.maxSurge | default "25%" }}
  progressDeadlineSeconds: {{ $cfg.progressDeadlineSeconds | default 600 }}
  {{- end }}
  {{- if eq $cfg.type "rollout" }}
  strategy:
    blueGreen:
      activeService: {{ $name }}
      previewService: {{ $name }}-preview
      autoPromotionEnabled: {{ $cfg.rollout.autoPromotionEnabled }}
  revisionHistoryLimit: {{ $cfg.rollout.revisionHistoryLimit }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "smartactivation.componentLabels" (dict "root" . "name" $name "component" "authservice") | nindent 8 }}
        app.kubernetes.io/version: {{ .Values.global.deployment.images.tag | quote }}
        {{- with .Values.customLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/{{ $name }}: {{ $cfg.securityContext.appArmorProfile }}
        {{- with .Values.customAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.deployment.images.imagePullSecret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.global.deployment.images.imagePullSecret.name }}
      {{- end }}
      serviceAccountName: {{ include "rpi.serviceAccountName" (dict "root" . "name" $name) }}
      {{- if $cfg.securityContext.enabled }}
      securityContext:
        runAsUser: {{ $cfg.securityContext.runAsUser }}
        runAsGroup: {{ $cfg.securityContext.runAsGroup }}
        fsGroup: {{ $cfg.securityContext.fsGroup }}
        runAsNonRoot: {{ $cfg.securityContext.runAsNonRoot }}
      {{- end }}
      terminationGracePeriodSeconds: 120
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: {{ $name }}
                topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ $name }}
      containers:
      - name: {{ $name }}
        image: {{ .Values.global.deployment.images.repository }}/{{ $name }}:{{ .Values.global.deployment.images.tag }}
        imagePullPolicy: {{ .Values.global.deployment.images.imagePullPolicy | default "IfNotPresent" }}
        livenessProbe:
          httpGet:
            path: /auth/health/live
            port: 9000
          periodSeconds: {{ $liveness.periodSeconds }}
          timeoutSeconds: {{ $liveness.timeoutSeconds }}
          failureThreshold: {{ $liveness.failureThreshold }}
        startupProbe:
          httpGet:
            path: /auth/health/live
            port: 9000
            scheme: HTTP
          periodSeconds: {{ $startup.periodSeconds }}
          failureThreshold: {{ $startup.failureThreshold }}
        {{- if $cfg.resources.enabled }}
        resources:
          {{- if and $cfg.resources.limits (ne $cfg.resources.limits.enabled false) }}
          limits:
            {{- with $cfg.resources.limits.cpu }}
            cpu: {{ . }}
            {{- end }}
            {{- with $cfg.resources.limits.memory }}
            memory: {{ . }}
            {{- end }}
          {{- end }}
          {{- if and $cfg.resources.requests (ne $cfg.resources.requests.enabled false) }}
          requests:
            {{- with $cfg.resources.requests.cpu }}
            cpu: {{ . }}
            {{- end }}
            {{- with $cfg.resources.requests.memory }}
            memory: {{ . }}
            {{- end }}
          {{- end }}
        {{- end }}
        ports:
        - containerPort: 8080
        {{- if $cfg.securityContext.enabled }}
        securityContext:
          privileged: {{ $cfg.securityContext.privileged }}
          allowPrivilegeEscalation: {{ $cfg.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ $cfg.securityContext.readOnlyRootFilesystem }}
#          capabilities:
#            drop:
#            {{- range $cfg.securityContext.capabilities.drop }}
#              - {{ . }}
#            {{- end }}
        {{- end }}
        env:
        {{- if .Values.global.deployment.podTimezone }}
        - name: TZ
          value: {{ .Values.global.deployment.podTimezone | quote }}
        {{- end }}
        {{- if eq .Values.databases.operational.provider "sqlserver" }}
        - name: KEYCLOAK_DATABASE_VENDOR
          value: mssql
        - name: KC_DB
          value: "mssql"
        - name: KC_DB_URL
          value: "jdbc:sqlserver://{{ .Values.databases.operational.server_host }};databaseName={{ $cfg.database_name }};"
        - name: KC_DB_USERNAME
          value: {{ .Values.databases.operational.server_username | quote }}
        {{- if not (eq .Values.secretsManagement.provider "sdk") }}
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "rpi.secrets.secretName" . | quote }}
              key: Operations_Database_Server_Password
        {{- end }}
        {{- end }}
        - name: KEYCLOAK_PRODUCTION
          value: "false"
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: {{ $cfg.username | quote }}
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "rpi.secrets.secretName" . | quote }}
              key: CDP_Keycloak_Admin_Password
        - name: KEYCLOAK_EXTRA_ARGS
          value: "-Dkeycloak.frontendUrl=https://{{ include "rpi.ingress.fqdn" (dict "host" $ingCfg.hosts.smartactivation "domain" $ingCfg.domain) }}"
        - name: KEYCLOAK_DATABASE_NAME
          value: {{ $cfg.database_name | quote }}
        - name: KEYCLOAK_PROXY_HEADERS
          value: "xforwarded"
        - name: KEYCLOAK_HOSTNAME_STRICT
          value: 'false'
        {{- include "rpi.cloudidentity.envvars" . | nindent 8 }}
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
      {{- end }}
      {{- if .Values.tolerations.enabled }}
      tolerations:
        - effect: NoSchedule
          key: {{ .Values.nodeSelector.key }}
          operator: Equal
          value: {{ .Values.nodeSelector.value }}
      {{- end }}
{{- end }}