{{- $diag := fromYaml (include "rpi.merged.diagnosticsMode" .) -}}
{{- $name := "net-utils" -}}

{{- if $diag.netutils.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redpoint-rpi.componentLabels" (dict "root" . "name" $name "component" "networkutils") | nindent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redpoint-rpi.componentLabels" (dict "root" . "name" $name "component" "networkutils") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        {{- include "redpoint-rpi.componentLabels" (dict "root" . "name" $name "component" "networkutils") | nindent 8 }}
        {{- with .Values.customLabels }}
        {{- toYaml . | nindent 8 }} 
        {{- end }}
    spec:
      {{- if .Values.global.deployment.images.imagePullSecret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.global.deployment.images.imagePullSecret.name }}
      {{- end }}
      serviceAccountName: {{ $name }}
      {{- with $diag.netutils.securityContext }}
      securityContext:
        runAsNonRoot: {{ .runAsNonRoot }}
        runAsUser: {{ .runAsUser }}
        runAsGroup: {{ .runAsGroup }}
      {{- end }}
      containers:
      - name: {{ $name }}
        image: rg1acrpub.azurecr.io/docker/redpointglobal/releases/net-utils:latest
        imagePullPolicy: {{  .Values.global.deployment.images.imagePullPolicy | default "IfNotPresent" }}
        volumeMounts:
        - name: tempdata
          mountPath: /tmp
        {{- with $diag.netutils.securityContext }}
        securityContext:
          runAsNonRoot: {{ .runAsNonRoot }}
          runAsUser: {{ .runAsUser }}
          runAsGroup: {{ .runAsGroup }}
          readOnlyRootFilesystem: {{ .readOnlyRootFilesystem }}
          allowPrivilegeEscalation: {{ .allowPrivilegeEscalation }}
          privileged: {{ .privileged }}
          {{- if or .capabilities.add .capabilities.drop }}
          capabilities:
            {{- if .capabilities.drop }}
            drop:
              {{- range .capabilities.drop }}
              - {{ . }}
              {{- end }}
            {{- end }}
            {{- if .capabilities.add }}
            add:
              {{- range .capabilities.add }}
              - {{ . }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: tempdata
        emptyDir: {}
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
      {{- end }}
      {{- if .Values.tolerations.enabled }}
      tolerations:
        - effect: NoSchedule
          key: {{ .Values.nodeSelector.key }}
          operator: Equal
          value: {{ .Values.nodeSelector.value }}
      {{- end }}
{{- end }}
