
# 1- Create Storage Class     
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rpitemptest            
parameters:
  directoryPerms: "755"          
  ensureUniqueDirectory: "true"   
  fileSystemId: fs-00f9e126b23d7fa08 
  gidRangeStart: "7000"                   
  gidRangeEnd: "8000"           
  provisioningMode: efs-ap     
  reuseAccessPoint: "false"       
  subPathPattern: ${.PVC.namespace}/${.PVC.name} 
provisioner: efs.csi.aws.com   
reclaimPolicy: Retain            
volumeBindingMode: Immediate  
allowVolumeExpansion: true 

---
# 2 Create Persistent VolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpifileexports
  namespace: redpoint-rpi 
spec:
  accessModes:
  - ReadWriteMany           
  resources:
    requests:
      storage: 50Gi                
  storageClassName: rpitemptest
  volumeMode: Filesystem  
