apiVersion: v1
kind: Service
metadata:
  name: rpi-realtime
  namespace: {{ include "custom.namespace" . }}
  labels:
    app: rpi-realtime
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-realtime