{{- if eq .Values.global.cloud "demo" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-configeditor
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {
      "OperationalDatabase": {
        "DatabaseType": "SQLServer",
        "PulseDatabaseName": "Pulse",
        "LoggingDatabaseName": "Pulse_Logging",
        "ConnectionSettings": {
          "SelectedDBType": "SQLServer",
          "Server": "rpiopsmssqlserver",
          "IsUsingCredentials": true,
          "Username": "sa",
          "Password": ".RedPoint2021",
          "DatabaseSchema": "dbo",
          "SQLServerSettings": {
            "Encrypt": true,
            "TrustServerCertificate": true
          }
        },
        "DeploymentSettings": {
          "IsUsingCustomDataFolder": false
        }
      },
      "UserManagement": {
        "UseNativeUserManagement": true,
        "UseExternalUserManagement": false
      }
    }
{{- end }}

---
{{- if eq .Values.global.cloud "amazon" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-configeditor
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {{- if eq .Values.databases.type "sqlserver" }}
    {
      "OperationalDatabase": {
        "DatabaseType": "SQLServer",
        "PulseDatabaseName": {{ .Values.databases.operationsDatabaseName | quote }},
        "LoggingDatabaseName": {{ .Values.databases.loggingDatabaseName | quote }},
        "ConnectionSettings": {
          "SelectedDBType": "SQLServer",
          "Server": {{ .Values.databases.serverhost | quote }},
          "IsUsingCredentials": true,
          "Username": {{ .Values.databases.username | quote }},
          "Password": {{ .Values.databases.password | quote }},
          "DatabaseSchema": "dbo",
          "SQLServerSettings": {
            "Encrypt": true,
            "TrustServerCertificate": true
          }
        },
        "DeploymentSettings": {
          "IsUsingCustomDataFolder": false
        }
      },
      "UserManagement": {
        "UseNativeUserManagement": true,
        "UseExternalUserManagement": false
      }
    }
    {{- end }}
    {{- if eq .Values.databases.type "amazonrds" }}
    {
      "OperationalDatabase": {
        "DatabaseType": "AmazonRDSSQL",
        "PulseDatabaseName": {{ .Values.databases.operationsDatabaseName | quote }},
        "LoggingDatabaseName": {{ .Values.databases.loggingDatabaseName | quote }},
        "ConnectionSettings": {
          "SelectedDBType": "AmazonRDSSQL",
          "Server": {{ .Values.databases.serverhost | quote }},
          "IsUsingCredentials": true,
          "Username": {{ .Values.databases.username | quote }},
          "Password": {{ .Values.databases.password | quote }},
          "DatabaseSchema": "dbo",
          "SQLServerSettings": {
            "Encrypt": true,
            "TrustServerCertificate": true
          }
        }
      },
      "UserManagement": {
        "UseNativeUserManagement": true,
        "UseExternalUserManagement": false
      }
    }
    {{- end }}
    {{- if eq .Values.databases.type "postgresql" }}
    {
      "OperationalDatabase": {
        "DatabaseType": "PostgreSQL",
        "PulseDatabaseName": "Pulse",
        "LoggingDatabaseName": "Pulse_Logging",
        "ConnectionSettings": {
          "SelectedDBType": "PostgreSQL",
          "Server": {{ .Values.databases.serverhost | quote }},
          "IsUsingCredentials": true,
          "Username": {{ .Values.databases.username | quote }},
          "Password": {{ .Values.databases.password | quote }},
          "Port": 5432
        }
      },
      "UserManagement": {
        "UseNativeUserManagement": true,
        "UseExternalUserManagement": false
      }
    }
    {{- end }}
{{- end }}

---
{{- if eq .Values.global.cloud "azure" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-configeditor
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {{- if eq .Values.databases.type "sqlserver" }}
    {
      "OperationalDatabase": {
        "DatabaseType": "SQLServer",
        "PulseDatabaseName": {{ .Values.databases.operationsDatabaseName | quote }},
        "LoggingDatabaseName": {{ .Values.databases.loggingDatabaseName | quote }},
        "ConnectionSettings": {
          "SelectedDBType": "SQLServer",
          "Server": {{ .Values.databases.serverhost | quote }},
          "IsUsingCredentials": true,
          "Username": {{ .Values.databases.username | quote }},
          "Password": {{ .Values.databases.password | quote }},
          "DatabaseSchema": "dbo",
          "SQLServerSettings": {
            "Encrypt": true,
            "TrustServerCertificate": true
          }
        },
        "DeploymentSettings": {
          "IsUsingCustomDataFolder": false
        }
      },
      "UserManagement": {
        "UseNativeUserManagement": true,
        "UseExternalUserManagement": false
      }
    }
    {{- end }}
    {{- if eq .Values.databases.type "azuresql" }}
    {
      "OperationalDatabase": {
        "DatabaseType": "AzureSQLDatabase",
        "PulseDatabaseName": {{ .Values.databases.operationsDatabaseName | quote }},
        "LoggingDatabaseName": {{ .Values.databases.loggingDatabaseName | quote }},
        "ConnectionSettings": {
          "SelectedDBType": "AzureSQLDatabase",
          "Server": {{ .Values.databases.serverhost | quote }},
          "IsUsingCredentials": true,
          "Username": {{ .Values.databases.username | quote }},
          "Password": {{ .Values.databases.password | quote }},
          "DatabaseSchema": "dbo",
          "SQLServerSettings": {
            "Encrypt": true,
            "TrustServerCertificate": true
          }
        }
      },
      "UserManagement": {
        "UseNativeUserManagement": true,
        "UseExternalUserManagement": false
      }
    }
    {{- end }}
    {{- if eq .Values.databases.type "postgresql" }}
    {
      "OperationalDatabase": {
        "DatabaseType": "PostgreSQL",
        "PulseDatabaseName": "Pulse",
        "LoggingDatabaseName": "Pulse_Logging",
        "ConnectionSettings": {
          "SelectedDBType": "PostgreSQL",
          "Server": {{ .Values.databases.serverhost | quote }},
          "IsUsingCredentials": true,
          "Username": {{ .Values.databases.username | quote }},
          "Password": {{ .Values.databases.password | quote }},
          "Port": 5432
        }
      },
      "UserManagement": {
        "UseNativeUserManagement": true,
        "UseExternalUserManagement": false
      }
    }
    {{- end }}
{{- end }}

---
---
{{- if eq .Values.global.cloud "google" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-configeditor
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {{- if eq .Values.databases.type "sqlserver" }}
    {
      "OperationalDatabase": {
        "DatabaseType": "SQLServer",
        "PulseDatabaseName": {{ .Values.databases.operationsDatabaseName | quote }},
        "LoggingDatabaseName": {{ .Values.databases.loggingDatabaseName | quote }},
        "ConnectionSettings": {
          "SelectedDBType": "SQLServer",
          "Server": {{ .Values.databases.serverhost | quote }},
          "IsUsingCredentials": true,
          "Username": {{ .Values.databases.username | quote }},
          "Password": {{ .Values.databases.password | quote }},
          "DatabaseSchema": "dbo",
          "SQLServerSettings": {
            "Encrypt": true,
            "TrustServerCertificate": true
          }
        },
        "DeploymentSettings": {
          "IsUsingCustomDataFolder": false
        }
      },
      "UserManagement": {
        "UseNativeUserManagement": true,
        "UseExternalUserManagement": false
      }
    }
    {{- end }}
    {{- if eq .Values.databases.type "googlecloudsql" }}
    {
      "OperationalDatabase": {
        "DatabaseType": "GoogleCloudSQL",
        "PulseDatabaseName": {{ .Values.databases.operationsDatabaseName | quote }},
        "LoggingDatabaseName": {{ .Values.databases.loggingDatabaseName | quote }},
        "ConnectionSettings": {
          "SelectedDBType": "GoogleCloudSQL",
          "Server": {{ .Values.databases.serverhost | quote }},
          "IsUsingCredentials": true,
          "Username": {{ .Values.databases.username | quote }},
          "Password": {{ .Values.databases.password | quote }},
          "DatabaseSchema": "dbo",
          "SQLServerSettings": {
            "Encrypt": true,
            "TrustServerCertificate": true
          }
        }
      },
      "UserManagement": {
        "UseNativeUserManagement": true,
        "UseExternalUserManagement": false
      }
    }
    {{- end }}
{{- end }}