apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-config-editor
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {
      "ClusterEnvironment": {
        "OperationalDatabase": {
          "DatabaseType": {{ .Values.appsettings.configeditor.ConnectionSettings.DatabaseType | quote }},
          "PulseDatabaseName": {{ .Values.appsettings.configeditor.ConnectionSettings.PulseDatabaseName | quote }},
          "LoggingDatabaseName": {{ .Values.appsettings.configeditor.ConnectionSettings.LoggingDatabaseName | quote }},
          "ConnectionSettings": {
            "SelectedDBType": {{ .Values.appsettings.configeditor.ConnectionSettings.DatabaseType | quote }},
            "Server": {{ .Values.appsettings.configeditor.ConnectionSettings.Server | quote }},
            "IsUsingCredentials": true,
            "Username": {{ .Values.appsettings.configeditor.ConnectionSettings.Username | quote }},
            "Password": {{ .Values.appsettings.configeditor.ConnectionSettings.Password | quote }},
            "SQLServerSettings": {
              "Encrypt": true,
              "TrustServerCertificate": true
            }
          }
        }
      }
    }