apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-rpi-callback-api
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
  {{- if eq .Values.appsettings.callbackapi.type "sqs" }}
    {
      "CallbackServiceConfig": {
        "QueueEnabled": true,
        "QueueProvider": {
          "ChannelLabel": {{ .Values.appsettings.callbackapi.settings.queueProvider.ChannelLabel | quote }},
          "CallbackServiceQueuePath": {{ .Values.appsettings.callbackapi.settings.sqs.CallbackServiceQueuePath | quote }},
          "CallbackServiceQueueSettings": {
            "Assembly": "RedPoint.Resonance.AWSQueueAccess",
            "Type": "RedPoint.Resonance.AWSQueueAccess.SQSQueueFactory",
            "Settings": [
              {
                "Key": "AccessKey",
                "Value": {{ .Values.appsettings.callbackapi.settings.sqs.accessKey | quote }}
              },
              {
                "Key": "SecretKey",
                "Value": {{ .Values.appsettings.callbackapi.settings.sqs.secretKey | quote }}
              },
              {
                "Key": "RegionEndpoint",
                "Value": {{ .Values.appsettings.callbackapi.settings.sqs.regionEndpoint | quote }}
              }
            ]
          }
        },
        "AllowedHosts": "*"
      }
    }
  {{- end }}