apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-rpi-execution-service
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {
      "Authentication": {
        "EnableRPIAuthentication": {{ .Values.appsettings.executionservice.EnableRPIAuthentication }},
        "OpenIdProviders": [
          {
            "Name": {{ .Values.appsettings.executionservice.OpenIdProviders.Name | quote }},
            "AuthorizationHost": {{ .Values.appsettings.executionservice.OpenIdProviders.AuthorizationHost | quote }},
            "ClientID": {{ .Values.appsettings.executionservice.OpenIdProviders.ClientID | quote }},
            "Audience": {{ .Values.appsettings.executionservice.OpenIdProviders.Audience | quote }},
            "RedirectURL": {{ .Values.appsettings.executionservice.OpenIdProviders.RedirectURL | quote }},
            "EnableRefreshTokens": {{ .Values.appsettings.executionservice.OpenIdProviders.EnableRefreshTokens }},
            "CustomScopes": {{ .Values.appsettings.executionservice.OpenIdProviders.CustomScopes }},
            "LogoutIdTokenParameter": {{ .Values.appsettings.executionservice.OpenIdProviders.LogoutIdTokenParameter | quote }},
            "ValidateIssuer": {{ .Values.appsettings.executionservice.OpenIdProviders.ValidateIssuer }},
            "ValidateAudience": {{ .Values.appsettings.executionservice.OpenIdProviders.ValidateAudience }}
          }
        ]
      },
        "DisableHttpRedirect": {{ .Values.appsettings.executionservice.DisableHttpRedirect }}
    }

