{{- if eq .Values.global.cloud "amazon" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-interactionapi
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {
      "Authentication": {
        "EnableRPIAuthentication": true,
        "RPIAuthentication": {
          "AuthorizationHost": "https://{{ .Values.ingress.hosts.client }}.{{ .Values.ingress.domain }}",
          "AuthMetaHttpHost": "http://rpi-interactionapi",
          "EnableTransportSecurityRequirement": false
        },
        "OpenIdProviders": [
          {
            "Name": {{ .Values.OpenIdProviders.Name | quote }},
            "AuthorizationHost": {{ .Values.OpenIdProviders.AuthorizationHost | quote }},
            "ClientID": {{ .Values.OpenIdProviders.ClientID | quote }},
            "Audience": {{ .Values.OpenIdProviders.Audience | quote }},
            "RedirectURL": "https://{{ .Values.ingress.hosts.client }}.{{ .Values.ingress.domain }}",
            "EnableRefreshTokens": {{ .Values.OpenIdProviders.EnableRefreshTokens }},
            "CustomScopes": {{ .Values.OpenIdProviders.CustomScopes | quote }},
            "LogoutIdTokenParameter": {{ .Values.OpenIdProviders.LogoutIdTokenParameter | quote }},
            "ValidateIssuer": {{ .Values.OpenIdProviders.ValidateIssuer }},
            "ValidateAudience": {{ .Values.OpenIdProviders.ValidateAudience }}
          }
        ]
      },
      "EnableSwagger": {{ .Values.interactionapi.enableSwagger }}
    }
{{- end }}

---
{{- if eq .Values.global.cloud "demo" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-interactionapi
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {
      "Authentication": {
        "EnableRPIAuthentication": true,
        "RPIAuthentication": {
          "AuthorizationHost": "https://rpi-interactionapi.redpointdemo.com",
          "AuthMetaHttpHost": "http://rpi-interactionapi",
          "EnableTransportSecurityRequirement": false
        },
        "OpenIdProviders": [
          {
            "Name": {{ .Values.OpenIdProviders.Name | quote }},
            "AuthorizationHost": "",
            "ClientID": "",
            "Audience": "",
            "RedirectURL": "https://rpi-client.redpointdemo.com",
            "EnableRefreshTokens": true,
            "CustomScopes": [],
            "LogoutIdTokenParameter": "id_token_hint",
            "ValidateIssuer": false,
            "ValidateAudience": true
          }
        ]
      },
      "EnableSwagger": true
    }
{{- end }}