apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-rpi-node-manager
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {
      "Authentication": {
        "EnableRPIAuthentication": {{ .Values.appsettings.nodemanager.EnableRPIAuthentication }},
        "OpenIdProviders": [
          {
            "Name": {{ .Values.appsettings.OpenIdProviders.Name | quote }},
            "AuthorizationHost": {{ .Values.appsettings.OpenIdProviders.AuthorizationHost | quote }},
            "ClientID": {{ .Values.appsettings.OpenIdProviders.ClientID | quote }},
            "Audience": {{ .Values.appsettings.OpenIdProviders.Audience | quote }},
            "RedirectURL": https://{{ .Values.ingress.hosts.client }}.{{ .Values.ingress.domain | quote }},
            "EnableRefreshTokens": {{ .Values.appsettings.OpenIdProviders.EnableRefreshTokens }},
            "CustomScopes": {{ .Values.appsettings.OpenIdProviders.CustomScopes | quote }},
            "LogoutIdTokenParameter": {{ .Values.appsettings.OpenIdProviders.LogoutIdTokenParameter | quote }},
            "ValidateIssuer": {{ .Values.appsettings.OpenIdProviders.ValidateIssuer }},
            "ValidateAudience": {{ .Values.appsettings.OpenIdProviders.ValidateAudience }}
          }
        ]
      },
      "DisableHttpRedirect": {{ .Values.appsettings.nodemanager.DisableHttpRedirect }}
    }

