{{- if .Values.databases.datawarehouse.autoCreateSecrets }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: odbc-config
data:
  odbc2.ini: |
    [ODBC]
    Trace=no

    [ODBC Data Sources]
    {{- if .Values.databases.datawarehouse.redshift.enabled }}
    {{- range .Values.databases.datawarehouse.redshift.connections }}
    {{ .name }}=Amazon Redshift DSN 64=Amazon Redshift (x64)
    {{- end }}
    {{- end }}

    {{- if .Values.databases.datawarehouse.bigquery.enabled }}
    {{- range .Values.databases.datawarehouse.bigquery.connections }}
    {{ .name }}=Simba ODBC Driver for Google BigQuery 64-bit
    {{- end }}
    {{- end }}

    {{- if .Values.databases.datawarehouse.databricks.enabled }}
    {{- range .Values.databases.datawarehouse.databricks.connections }}
    {{ .name }}=Simba Apache Spark ODBC Connector
    {{- end }}
    {{- end }}

    {{- if .Values.databases.datawarehouse.redshift.enabled }}
    {{- range .Values.databases.datawarehouse.redshift.connections }}

    [{{ .name }}]
    Description=Amazon Redshift ODBC Driver for {{ .name }}
    Driver=/app/odbc-lib/redshift/lib/libamazonredshiftodbc64.so
    Server={{ .server }}
    Port={{ .port }}
    Database={{ .database }}
    UID={{ .username }}
    PWD={{ .password }}
    locale=en-US
    {{- end }}
    {{- end }}

    {{- if .Values.databases.datawarehouse.bigquery.enabled }}
    {{- range .Values.databases.datawarehouse.bigquery.connections }}

    [{{ .name }}]
    Description=Simba ODBC Driver for Google BigQuery (64-bit) DSN
    Driver=/app/odbc-lib/bigquery/SimbaODBCDriverforGoogleBigQuery64/lib/libgooglebigqueryodbc_sb64.so
    Catalog={{ .projectId }}
    SQLDialect={{ .sqlDialect }}
    AllowLargeResults={{ .allowLargeResults }}
    LargeResultsDataSetId={{ .largeResultsDataSetId }}
    LargeResultsTempTableExpirationTime={{ .largeResultsTempTableExpirationTime }}
    OAuthMechanism={{ .OAuthMechanism }}
    Email={{ .serviceAccountEmail }}
    KeyFilePath={{ .ConfigMapFilePath }}/{{ .keyName }}
    {{- end }}
    {{- end }}
    
    {{- if .Values.databases.datawarehouse.databricks.enabled }}
    {{- range .Values.databases.datawarehouse.databricks.connections }}

    [{{ .name }}]
    Driver=/app/odbc-lib/simba/spark/lib/libsparkodbc_sb64.so
    SparkServerType=3
    Host={{ .host }}
    Port={{ .port }}
    Schema={{ .schema }}
    SSL=1
    Min_TLS=1.2 
    ThriftTransport=2
    AuthMech={{ .authMechanism }}
    UID={{ .username }}
    PWD={{ .password }}
    TrustedCerts=/app/odbc-lib/simba/spark/lib/cacerts.pem
    UseSystemTrustStore=0
    HTTPPath={{ .httpPath }}
    {{- end }}
    {{- end }}
{{- end }}