{{- if eq .Values.global.cloud "amazon" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-realtimeapi
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |-
    {
      "RealtimeAPIConfiguration": {
        "AppSettings": {
          "RealtimeAgentInProcessEnabled": true,
          "RealtimeAgentAuthToken": "{{ .Values.realtime.rpiAuthToken }}",
          "EnableHelpPages": {{ .Values.realtime.enableHelpPages }},
          "DecisionCacheDuration": {{ .Values.realtime.decisionCacheDuration }},
          "RPIClientID": "{{ .Values.realtime.rpiClientID }}",
          "RPIAuthToken": "{{ .Values.realtime.rpiAuthToken }}",
          "EnableAuditMetricsInHeaders": {{ .Values.realtime.enableAuditMetricsInHeaders }},
          "EnableEventListening": {{ .Values.realtime.enableEventListening }}
        },
        {{- if eq .Values.queueProviders.type "azureeventhubs" }}
        "Queues": {
          "FormQueuePath": {{ .Values.queueNames.formQueuePath | quote }},
          "EventsQueuePath": {{ .Values.queueNames.eventsQueuePath | quote }},
          "CacheOutputQueueEnabled": true,
          "CacheOutputQueuePath": {{ .Values.queueNames.cacheOutputQueuePath | quote }},
          "RecommendationsQueuePath": {{ .Values.queueNames.recommendationsQueuePath | quote }},
          "ClientQueueSettings": {
            "Assembly": "RedPoint.Azure.Server",
            "Type": "RedPoint.Azure.Server.AzureEventHubs.AzureEventHubsFactory",
            "Settings": [
              {
                "Key": "EventHubName",
                "Value": {{ .Values.queueProviders.azureeventhubs.eventHubName | quote }}
              },
              {
                "Key": "EventHubConnectionString",
                "Value": {{ .Values.queueProviders.azureeventhubs.connectionString | quote }}
              }
            ]
          },
          "ListenerQueuePath": {{ .Values.queueNames.listenerQueuePath | quote }},
          "ListenerQueueSettings": {
            "Assembly": "RedPoint.Resonance.AzureEventHubsAccess",
            "Type": "RedPoint.Azure.Server.AzureEventHubs.AzureEventHubsFactory",
            "Settings": [
              {
                "Key": "EventHubName",
                "Value": {{ .Values.queueProviders.azureeventhubs.eventHubName | quote }}
              },
              {
                "Key": "EventHubConnectionString",
                "Value": {{ .Values.queueProviders.azureeventhubs.connectionString | quote }}
              }
            ]
          }
        },
        {{- end }}
        {{- if eq .Values.queueProviders.type "amazonsqs" }}
        "Queues": {
          "FormQueuePath": {{ .Values.queueNames.formQueuePath | quote }},
          "EventsQueuePath": {{ .Values.queueNames.eventsQueuePath | quote }},
          "CacheOutputQueueEnabled": true,
          "CacheOutputQueuePath": {{ .Values.queueNames.cacheOutputQueuePath | quote }},
          "RecommendationsQueuePath": {{ .Values.queueNames.recommendationsQueuePath | quote }},
          "ClientQueueSettings": {
            "Assembly": "RedPoint.Amazon.Server",
            "Type": "RedPoint.Amazon.Server.AWSQueue.SQSQueueFactory",
            "Settings": [
              {
                "Key": "AccessKey",
                "Value": {{ .Values.queueProviders.amazonsqs.accessKey | quote }}
              },
              {
                "Key": "SecretKey",
                "Value": {{ .Values.queueProviders.amazonsqs.secretKey | quote }}
              },
              {
                "Key": "RegionEndpoint",
                "Value": {{ .Values.queueProviders.amazonsqs.regionEndpoint | quote }}
              }
            ]
          },
          "ListenerQueuePath": {{ .Values.queueNames.listenerQueuePath | quote }},
          "ListenerQueueSettings": {
            "Assembly": "RedPoint.Amazon.Server",
            "Type": "RedPoint.Amazon.Server.AWSQueue.SQSQueueFactory",
            "Settings": [
              {
                "Key": "AccessKey",
                "Value": {{ .Values.queueProviders.amazonsqs.accessKey | quote }}
              },
              {
                "Key": "SecretKey",
                "Value": {{ .Values.queueProviders.amazonsqs.secretKey | quote }}
              },
              {
                "Key": "RegionEndpoint",
                "Value": {{ .Values.queueProviders.amazonsqs.regionEndpoint | quote }}
              }
            ]
          }
        },
        {{- end }}
        {{- if eq .Values.queueProviders.type "rabbitmq" }}
        "Queues": {
          "FormQueuePath": {{ .Values.queueNames.formQueuePath | quote }},
          "EventsQueuePath": {{ .Values.queueNames.eventsQueuePath | quote }},
          "CacheOutputQueueEnabled": true,
          "CacheOutputQueuePath": {{ .Values.queueNames.cacheOutputQueuePath | quote }},
          "RecommendationsQueuePath": {{ .Values.queueNames.recommendationsQueuePath | quote }},
          "ClientQueueSettings": {
            "Assembly": "RedPoint.Resonance.RabbitMQAccess",
            "Type": "RedPoint.Resonance.RabbitMQAccess.RabbitMQFactory",
            "Settings": [
              {
                "Key": "HostName",
                "Value": {{ .Values.queueProviders.rabbitmq.hostName | quote }}
              },
              {
                "Key": "VirtualHost",
                "Value": "/"
              },
              {
                "Key": "UserName",
                "Value": {{ .Values.queueProviders.rabbitmq.username | quote }}
              },
              {
                "Key": "Password",
                "Value": {{ .Values.queueProviders.rabbitmq.password | quote }}
              }
            ]
          },
          "ListenerQueuePath": {{ .Values.queueNames.listenerQueuePath | quote }},
          "ListenerQueueSettings": {
            "Assembly": "RedPoint.Resonance.RabbitMQAccess",
            "Type": "RedPoint.Resonance.RabbitMQAccess.RabbitMQFactory",
            "Settings": [
              {
                "Key": "HostName",
                "Value": {{ .Values.queueProviders.rabbitmq.hostName | quote }}
              },
              {
                "Key": "VirtualHost",
                "Value": "/"
              },
              {
                "Key": "UserName",
                "Value": {{ .Values.queueProviders.rabbitmq.username | quote }}
              },
              {
                "Key": "Password",
                "Value": {{ .Values.queueProviders.rabbitmq.password | quote }}
              }
            ]
          }
        },
        {{- end }}
        {{- if eq .Values.cacheProviders.type "mongodb" }}
        "CacheSettings": {
          "Caches": [
            {
              "Name": "Default",
              "Assembly": "RedPoint.Resonance.MongoDBCache",
              "Class": "RedPoint.Resonance.MongoDBCache.MongoDBCacheHandler",
              "Settings": [
                {
                  "Key": "Database",
                  "Value": {{ .Values.cacheProviders.mongodb.databaseName | quote }}
                },
                {
                  "Key": "ConnectionString",
                  "Value": {{ .Values.cacheProviders.mongodb.ConnectionString | quote }}
                },
                {
                  "Key": "CollectionName",
                  "Value": {{ .Values.cacheProviders.mongodb.CollectionName | quote }}
                }
              ]
            }
          ]
        },
        {{- end }}
        {{- if eq .Values.cacheProviders.type "inMemorySql" }}
        "CacheSettings": {
          "Caches": [
            {
              "Name": "InMemorySQL",
              "Assembly": "RedPoint.Resonance.Web.Shared",
              "Class": "RedPoint.Resonance.Web.Shared.Cache.SQLServerCache",
              "Settings": [
                {
                  "Key": "ConnectionString",
                  "Value": {{ .Values.cacheProviders.inMemorySql.connectionString | quote }}
                }
              ]
            }
          ]
        }
        {{- end }}
        {{- if eq .Values.cacheProviders.type "cassandra" }}
        "CacheSettings": {
          "Caches": [
            {
              "Name": "Default",
              "Assembly": "Redpoint.Resonance.CassandraCachehe",
              "Class": "Redpoint.CassandraCache.CassandraCacheHandler",
              "Settings": [
                {
                  "Key": "Keyspace",
                  "Value": {{ .Values.cacheProviders.cassandra.keyspace | quote }}
                },
                {
                  "Key": "ContactPoints",
                  "Value": {{ .Values.cacheProviders.cassandra.contactpoints | quote }}
                },
                {
                  "Key": "UserName",
                  "Value": {{ .Values.cacheProviders.cassandra.username | quote }}
                },
                {
                  "Key": "Password",
                  "Value": {{ .Values.cacheProviders.cassandra.password | quote }}
                }
              ]
            }
          ]
        },
        {{- end }}
        {{- if eq .Values.cacheProviders.type "azurecosmosdb" }}
        "CacheSettings": {
          "Caches": [
            {
              "Name": "AzureCosmosDB",
              "Assembly": "RedPoint.Resonance.DocumentDBCache",
              "Class": "RedPoint.Resonance.DocumentDbCache.DocumentDBCacheHandler",
              "Settings": [
                {
                  "Key": "DatabaseId",
                  "Value": {{ .Values.cacheProviders.azurecosmosdb.databaseId | quote }}
                },
                {
                  "Key": "ConnectionString",
                  "Value": {{ .Values.cacheProviders.azurecosmosdb.connectionString | quote }}
                },
                {
                  "Key": "ContainerName",
                  "Value": {{ .Values.cacheProviders.azurecosmosdb.containerName | quote }}
                }
              ]
            }
          ]
        }
        {{- end }}
        {{- if eq .Values.cacheProviders.type "redis" }}
        "CacheSettings": {
          "Caches": [
            {
              "Name": "Redis",
              "Assembly": "RedPoint.Resonance.RedisCache",
              "Class": "RedPoint.Resonance.RedisCache.RedisCacheHandler",
              "Settings": [
                {
                  "Key": "IPAddress",
                  "Value": {{ .Values.cacheProviders.redis.hostName | quote }}
                }
              ]
            }
          ]
        },
        {{- end }}
        {{- if eq .Values.cacheProviders.type "azureredis" }}
        "CacheSettings": {
          "Caches": [
            {
              "Name": "AzureRedis",
              "Assembly": "RedPoint.Azure.Server",
              "Class": "RedPoint.Azure.Server.AzureRedisCache.AzureRedisCacheHandler",
              "Settings": [
                {
                  "Key": "ConnectionString",
                  "Value": {{ .Values.cacheProviders.azureredis.connectionString | quote }}
                },
                "Key": "DisableMGET",
                "Value": {{ .Values.cacheProviders.azureredis.disableMGET}}
                }
              ]
            }
            }
          ]
        },
        {{- end }}
        {{- if eq .Values.cacheProviders.type "mongodb" }}
        "DataMaps": [
          {
            "Type": "Visitor Profile",
            "Cache": "Default",
            "DaysToPersist": 200,
            "CompressData": false
          },
          {
            "Type": "Visitor History",
            "Cache": "Default",
            "DaysToPersist": 365,
            "CompressData": false
          },
          {
            "Type": "Non Visitor Data",
            "Cache": "Default",
            "DaysToPersist": 365
          },
          {
            "Type": "Product Recommendations",
            "Cache": "Default",
            "DaysToPersist": 365
          }
        ]
      },
      {{- end }}
      {{- if eq .Values.cacheProviders.type "redis" }}
      "DataMaps": [
        {
          "Type": "Visitor Profile",
          "Cache": "Redis",
          "DaysToPersist": 200,
          "CompressData": false
        },
        {
          "Type": "Visitor History",
          "Cache": "Redis",
          "DaysToPersist": 365,
          "CompressData": false
        },
        {
          "Type": "Non Visitor Data",
          "Cache": "Redis",
          "DaysToPersist": 365
        },
        {
          "Type": "Product Recommendations",
          "Cache": "Redis",
          "DaysToPersist": 365
        }
      ]
    },
    {{- end }}
    {{- if eq .Values.cacheProviders.type "azureredis" }}
      "DataMaps": [
        {
          "Type": "Visitor Profile",
          "Cache": "AzureRedis",
          "DaysToPersist": 200,
          "CompressData": false
        },
        {
          "Type": "Visitor History",
          "Cache": "AzureRedis",
          "DaysToPersist": 365,
          "CompressData": false
        },
        {
          "Type": "Non Visitor Data",
          "Cache": "AzureRedis",
          "DaysToPersist": 365
        },
        {
          "Type": "Product Recommendations",
          "Cache": "AzureRedis",
          "DaysToPersist": 365
        }
      ]
    },
    {{- end }}
    {{- if eq .Values.cacheProviders.type "cassandra" }}
      "DataMaps": [
        {
          "Type": "Visitor Profile",
          "Cache": "Default",
          "DaysToPersist": 200,
          "CompressData": false
        },
        {
          "Type": "Visitor History",
          "Cache": "Default",
          "DaysToPersist": 365,
          "CompressData": false
        },
        {
          "Type": "Non Visitor Data",
          "Cache": "Default",
          "DaysToPersist": 365
        },
        {
          "Type": "Product Recommendations",
          "Cache": "Default",
          "DaysToPersist": 365
        }
      ]
    },
    {{- end }}
    "Authentication": {
      "DisableHttpRedirect": true,
      "EnableOAuth": false
    }
    }
{{- end }}

---
{{- if eq .Values.global.cloud "demo" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-realtimeapi
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |-
    {
      "RealtimeAPIConfiguration": {
        "AppSettings": {
          "RealtimeAgentInProcessEnabled": true,
          "RealtimeAgentAuthToken": "a8155b10-c073-4147-8095-0f0033c58ae8",
          "EnableHelpPages": true,
          "DecisionCacheDuration": 0,
          "PluginAssemblyPath": "",
          "RPIClientID": "11111111-1111-1111-1111-111111111111",
          "RPIAuthToken": "a8155b10-c073-4147-8095-0f0033c58ae8",
          "EnableAuditMetricsInHeaders": true,
          "EnableEventListening": true
        },
        "Queues": {
          "FormQueuePath": "RPIWebFormSubmission",
          "EventsQueuePath": "RPIWebEvents",
          "CacheOutputQueueEnabled": true,
          "CacheOutputQueuePath": "RPIWebCacheData",
          "RecommendationsQueuePath": "RPIWebRecommendations",
          "ClientQueueSettings": {
            "Assembly": "RedPoint.Resonance.RabbitMQAccess",
            "Type": "RedPoint.Resonance.RabbitMQAccess.RabbitMQFactory",
            "Settings": [
              {
                "Key": "HostName",
                "Value": "rpi-queuereader"
              },
              {
                "Key": "VirtualHost",
                "Value": "/"
              },
              {
                "Key": "UserName",
                "Value": "redpointdev"
              },
              {
                "Key": "Password",
                "Value": ".RedPoint2021"
              }
            ]
          },
          "ListenerQueuePath": {{ .Values.queueNames.listenerQueuePath | quote }},
          "ListenerQueueSettings": {
            "Assembly": "RedPoint.Resonance.RabbitMQAccess",
            "Type": "RedPoint.Resonance.RabbitMQAccess.RabbitMQFactory",
            "Settings": [
              {
                "Key": "HostName",
                "Value": "rpi-queuereader"
              },
              {
                "Key": "VirtualHost",
                "Value": "/"
              },
              {
                "Key": "UserName",
                "Value": "redpointdev"
              },
              {
                "Key": "Password",
                "Value": ".RedPoint2021"
              }
            ]
          }
        },
        "CacheSettings": {
          "Caches": [
            {
              "Name": "Redis",
              "Assembly": "RedPoint.Resonance.RedisCache",
              "Class": "RedPoint.Resonance.RedisCache.RedisCacheHandler",
              "Settings": [
                {
                  "Key": "IPAddress",
                  "Value": "rpi-rtdrediscache"
                }
              ]
            }
          ]
        },
        "DataMaps": [
          {
            "Type": "Visitor Profile",
            "Cache": "Redis",
            "DaysToPersist": 200,
            "CompressData": false
          },
          {
            "Type": "Visitor History",
            "Cache": "Redis",
            "DaysToPersist": 365,
            "CompressData": false
          },
          {
            "Type": "Non Visitor Data",
            "Cache": "Redis",
            "DaysToPersist": 365
          },
          {
            "Type": "Product Recommendations",
            "Cache": "Redis",
            "DaysToPersist": 365
          }
        ]
      },
    "Authentication": {
      "DisableHttpRedirect": true,
      "EnableOAuth": false
    }
    }
{{- end }}
