{{- if .Values.appsettings.configeditor.EnableDemoSQLServer }}
apiVersion: v1
kind: Service
metadata:
  name: sql-rpi-ops
  namespace: redpoint-rpi
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: sql-rpi-ops # name of the StatefulSet workload, the SQL Server instance name is derived from this. We suggest to keep this name same as the .spec.template.metadata.labels, .spec.selector.matchLabels and .spec.serviceName to avoid confusion.
 namespace: redpoint-rpi
spec:
 serviceName: "sql-rpi-ops"
 replicas: 1 
 selector:
  matchLabels:
   app: mssql  
 template:
  metadata:
   labels:
    app: mssql 
  spec:
   securityContext:
     fsGroup: 10001
   containers:
   - name: mssql 
     image: mcr.microsoft.com/mssql/server:2019-latest
     ports:
     - containerPort: 1433
       name: tcpsql
     env:
     - name: ACCEPT_EULA
       value: "Y"
     - name: MSSQL_ENABLE_HADR
       value: "0"
     - name: MSSQL_AGENT_ENABLED
       value: "0"
     - name: MSSQL_SA_PASSWORD
       value: "MyC0m9l&xP@ssw0rd"
     volumeMounts:
     - name: sql-rpi-ops
       mountPath: "/var/opt/mssql"
 volumeClaimTemplates:
   - metadata:
      name: sql-rpi-ops
     spec:
      accessModes:
      - ReadWriteOnce
      resources:
       requests:
        storage: 8Gi
{{- end }}