---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rpi-helpdocs
  namespace: {{ .Values.global.namespace }}

---
{{- if eq .Values.global.deployment_type "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-helpdocs
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.application.name }}
    env: {{ .Values.application.environment }}
    version: {{ .Values.application.version | quote }}
spec:
  replicas: {{ .Values.application.replicaCount.helpdocs }}
  selector:
    matchLabels:
      app: rpi-helpdocs
      env: {{ .Values.application.environment }}
      version: {{ .Values.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-helpdocs
        env: {{ .Values.application.environment }}
        version: {{ .Values.application.version | quote }}
    spec:
      imagePullSecrets:
        - name: docker-io
      serviceAccountName: sa-rpi-helpdocs
      containers:
      - name: rpi-helpdocs
        image: rpspeastus2acr.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-core-help:{{ .Values.global.image_tag_docs }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        ports:
        - containerPort: 80
          name: web-port
          protocol: TCP
      hostname: rpi-helpdocs
{{- end }}

---
{{- if eq .Values.global.deployment_type "client" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-helpdocs
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.application.name }}
    env: {{ .Values.application.environment }}
    version: {{ .Values.application.version | quote }}
spec:
  replicas: {{ .Values.application.replicaCount.helpdocs }}
  selector:
    matchLabels:
      app: rpi-helpdocs
      env: {{ .Values.application.environment }}
      version: {{ .Values.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-helpdocs
        env: {{ .Values.application.environment }}
        version: {{ .Values.application.version | quote }}
    spec:
      imagePullSecrets:
        - name: docker-io
      serviceAccountName: sa-rpi-helpdocs
      containers:
      - name: rpi-helpdocs
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-core-help:{{ .Values.global.image_tag_docs }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        ports:
        - containerPort: 80
          name: web-port
          protocol: TCP
      hostname: rpi-helpdocs
{{- end }}
