---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rpi-helpdocs
  namespace: {{ .Values.global.namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: rpi-helpdocs
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-helpdocs
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rpi-helpdocs

---
{{- if eq .Values.global.deploymentType "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-helpdocs
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.application.name }}
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: rpi-helpdocs
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-helpdocs
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      serviceAccountName: sa-rpi-helpdocs
      containers:
      - name: rpi-helpdocs
        image: rpspeastus2acr.azurecr.io/docker/redpointinteraction/7-2/prod/redpoint-interaction-core-help:{{ .Values.global.image_tag_docs_internal }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 80
          name: web-port
          protocol: TCP
      hostname: rpi-helpdocs
      nodeSelector:
        pool: rgoc-eus2
      tolerations:
        - effect: NoSchedule
          key: pool
          operator: Equal
          value: rgoc-eus2
{{- end }}

---
{{- if eq .Values.global.deploymentType "client" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-helpdocs
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.application.name }}
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: rpi-helpdocs
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-helpdocs
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: sa-rpi-helpdocs
      containers:
      - name: rpi-helpdocs
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-core-help:{{ .Values.global.image_tag_docs_client }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 80
          name: web-port
          protocol: TCP
      hostname: rpi-helpdocs
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
