{{- if eq .Values.global.cloudProvider "azure" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpi-fileoutputdir
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rpi-fileoutputdir
  resources:
    requests:
      storage: {{ .Values.appsettings.storage.size.rpi_output_directory }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rpi-fileoutputdir
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=0
- gid=0
- mfsymlinks
- cache=strict
- actimeo=30
parameters:
  skuName: Premium_LRS
provisioner: {{ .Values.appsettings.storage.class.azure }}
{{- end }}


{{- if eq .Values.global.cloudProvider "google" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rpi-fileoutputdir
provisioner: {{ .Values.appsettings.storage.class.google }}
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  network: default

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rpi-fileoutputdir
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: rpi-fileoutputdir
  resources:
    requests:
      storage: {{ .Values.appsettings.storage.size.rpi_output_directory }}
{{- end }}

---
{{- if eq .Values.global.cloudProvider "amazon" }}
apiVersion: v1
kind: PersistentVolume
metadata:
name: rpi-fileoutputdir
spec:
capacity:
storage: {{ .Values.appsettings.storage.size.rpi_output_directory }}
accessModes:
- ReadWriteMany
persistentVolumeReclaimPolicy: Retain
mountOptions:
- dir_mode=0777
- file_mode=0777
- vers=3.0
csi:
driver: {{ .Values.appsettings.storage.class.amazon.provisioner }}
readOnly: false
volumeHandle: {{ .Values.appsettings.storage.class.amazon.volumeHandle }} 

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rpi-fileoutputdir
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.appsettings.storage.size.rpi_output_directory }}
  volumeName: rpi-fileoutputdir
  storageClassName: smb
{{- end }}