{{- if .Values.realtimeapi.queueProvider.rabbitmq.internal }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rpi-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: rpi-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-rabbitmq
spec:
  ports:
  - name: http
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: console
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rpi-rabbitmq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-rabbitmq
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-rabbitmq
spec:
  replicas: {{ .Values.realtimeapi.queueProvider.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: rpi-rabbitmq
  template:
    metadata:
      labels:
        app: rpi-rabbitmq
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: rpi-rabbitmq
      containers:
      - name: rpi-rabbitmq
        image: {{ .Values.global.deployment.images.rabbitmq }}:{{ .Values.global.deployment.images.tag }}
        imagePullPolicy: {{  .Values.global.deployment.images.imagePullPolicy }}
        ports:
        - name: port-one
          containerPort: 5672
          protocol: TCP
        - name: port-two
          containerPort: 15672
          protocol: TCP
        {{- if .Values.realtimeapi.queueProvider.rabbitmq.resources.enabled }}
        resources:
          {{- if .Values.realtimeapi.queueProvider.rabbitmq.resources.limits }}
          limits:
            {{- if .Values.realtimeapi.queueProvider.rabbitmq.resources.limits.cpu }}
            cpu: {{ .Values.realtimeapi.queueProvider.rabbitmq.resources.limits.cpu }}
            {{- end }}
            {{- if .Values.realtimeapi.queueProvider.rabbitmq.resources.limits.memory }}
            memory: {{ .Values.realtimeapi.queueProvider.rabbitmq.resources.limits.memory }}
            {{- end }}
          {{- end }}
          {{- if .Values.realtimeapi.queueProvider.rabbitmq.resources.requests }}
          requests:
            {{- if .Values.realtimeapi.queueProvider.rabbitmq.resources.requests.cpu }}
            cpu: {{ .Values.realtimeapi.queueProvider.rabbitmq.resources.requests.cpu }}
            {{- end }}
            {{- if .Values.realtimeapi.queueProvider.rabbitmq.resources.requests.memory }}
            memory: {{ .Values.realtimeapi.queueProvider.rabbitmq.resources.requests.memory }}
            {{- end }}
          {{- end }}
        {{- end }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.realtimeapi.queueProvider.rabbitmq.username | quote }}
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cloudIdentity.secretsManagement.secretName | quote }}
              key: RABBITMQ_Password
        - name: RABBITMQ_DEFAULT_VHOST
          value: {{ .Values.realtimeapi.queueProvider.rabbitmq.virtualHost | quote }}
        livenessProbe:
          exec:
            command:
            - "rabbitmq-diagnostics"
            - "-q"
            - "ping"
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
      {{- end }}
      {{- if .Values.tolerations.enabled }}
      tolerations:
        - effect: NoSchedule
          key: {{ .Values.nodeSelector.key }}
          operator: Equal
          value: {{ .Values.nodeSelector.value }}
      {{- end }}
{{- end }}