apiVersion: v1
kind: Service
metadata:
  name: rpi-callback-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-callback-api
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-callback-api


---
{{- if eq .Values.global.deploymentType "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-callback-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-callback-api
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.replicas.callbackapi }}
  selector:
    matchLabels:
      app: rpi-callback-api
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-callback-api
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      serviceAccountName: sa-redpoint-rpi
      securityContext:
        runAsNonRoot: true
        runAsUser: 7777
        runAsGroup: 7777
      containers:
      - env:
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sql-rpiops-connstring
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sql-rpiops-connstring
        image: rpspeastus2acr.azurecr.io/docker/redpointinteraction/7-3/prod/redpoint-interaction-plugins-callbackservicewebapi:{{ .Values.global.image_tag_internal }}
        imagePullPolicy: Always
        name: config-editor
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        volumeMounts:
          - name: rpi-callback-api
            mountPath: /app/appsettings
      volumes:
        - name: rpi-callback-api
          configMap:
            name: cm-rpi-callbackapi
      nodeSelector:
        pool: rgoc-eus2
      tolerations:
        - effect: NoSchedule
          key: pool
          operator: Equal
          value: rgoc-eus2
{{- end }}


{{- if eq .Values.global.deploymentType "client" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-callback-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-callback-api
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.replicas.callbackapi }}
  selector:
    matchLabels:
      app: rpi-callback-api
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-callback-api
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      imagePullSecrets:
      - name: redpoint-rpi
      serviceAccountName: sa-rpi-callback-api
      securityContext:
        runAsNonRoot: true
        runAsUser: 7777
        runAsGroup: 7777
      containers:
      - env:
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sql-rpiops-connstring
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sql-rpiops-connstring
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-plugins-callbackservicewebapi:{{ .Values.global.image_tag_client }}
        imagePullPolicy: Always
        name: config-editor
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        volumeMounts:
          - name: rpi-callback-api
            mountPath: /app/appsettings
      volumes:
        - name: rpi-callback-api
          configMap:
            name: cm-rpi-callbackapi
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}