{{- if eq .Values.global.deploymentType "internal" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.global.namespace }}
provisioner: file.csi.azure.com 
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Premium_LRS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpifileoutputdir
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rpifileoutputdir
  resources:
    requests:
      storage: "100"
{{- end }}


