apiVersion: v1
kind: Service
metadata:
  name: rpi-nodemanager
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-nodemanager
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-nodemanager
    
---
{{- if eq .Values.global.cloud "demo" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-nodemanager
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-nodemanager
spec:
  replicas: {{ .Values.replicas.nodemanager }}
  selector:
    matchLabels:
      app: rpi-nodemanager
  template:
    metadata:
      labels:
        app: rpi-nodemanager
    spec:
      serviceAccountName: redpoint-rpi
      imagePullSecrets:
        - name: redpoint-rpi
      containers:
      - env:
        - name: RPIClient__applicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: Logging__Database__LogLevel__Default
          value: "Error"
        - name: RealtimeAPIAddressOverride
          value: "http://rpi-realtimeapi"
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: database-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: database-secrets
        - name: Authentication__EnableRPIAuthentication
          value: "true"
        - name: DisableHttpRedirect
          value: "true"
        {{- if eq .Values.databases.type "postgresql" }}
        - name: RPI_OperationalDatabaseType
          value: "PostgreSQL"
        {{- end }}
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-node-manager:{{ .Values.global.image_tag }}
        imagePullPolicy: Always
        name: node-manager
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
{{- end }}

---
{{- if eq .Values.global.cloud "amazon" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-nodemanager
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-nodemanager
spec:
  replicas: {{ .Values.replicas.nodemanager }}
  selector:
    matchLabels:
      app: rpi-nodemanager
  template:
    metadata:
      labels:
        app: rpi-nodemanager
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: redpoint-rpi
      containers:
      - env:
        - name: RPIClient__applicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: Logging__Database__LogLevel__Default
          value: "Error"
        {{- if eq .Values.databases.type "postgresql" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: postgresql-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: postgresql-secrets
        {{- end }}
        {{- if eq .Values.databases.type "azuresqlserver" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sqlserver-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sqlserver-secrets
        {{- end }}
        {{- if eq .Values.databases.type "amazonrdssql" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sqlserver-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sqlserver-secrets
        {{- end }}
        {{- if eq .Values.databases.type "googlecloudsql" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sqlserver-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sqlserver-secrets
        {{- end }}
        - name: Authentication__EnableRPIAuthentication
          value: "true"
        - name: DisableHttpRedirect
          value: "true"
        - name: RealtimeAPIAddressOverride
          value: "http://rpi-realtimeapi"
        {{- if eq .Values.databases.type "postgresql" }}
        - name: RPI_OperationalDatabaseType
          value: "PostgreSQL"
        {{- end }}
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-node-manager:{{ .Values.global.image_tag }}
        imagePullPolicy: Always
        name: node-manager
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

---
{{- if eq .Values.global.cloud "azure" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-nodemanager
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-nodemanager
spec:
  replicas: {{ .Values.replicas.nodemanager }}
  selector:
    matchLabels:
      app: rpi-nodemanager
  template:
    metadata:
      labels:
        app: rpi-nodemanager
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: redpoint-rpi
      containers:
      - env:
        - name: RPIClient__applicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: Logging__Database__LogLevel__Default
          value: "Error"
        {{- if eq .Values.databases.type "postgresql" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: postgresql-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: postgresql-secrets
        {{- end }}
        {{- if eq .Values.databases.type "azuresqlserver" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sqlserver-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sqlserver-secrets
        {{- end }}
        {{- if eq .Values.databases.type "amazonrdssql" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sqlserver-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sqlserver-secrets
        {{- end }}
        {{- if eq .Values.databases.type "googlecloudsql" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sqlserver-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sqlserver-secrets
        {{- end }}
        - name: RealtimeAPIAddressOverride
          value: "http://rpi-realtimeapi"
        - name: Authentication__EnableRPIAuthentication
          value: "true"
        - name: DisableHttpRedirect
          value: "true"
        {{- if eq .Values.databases.type "postgresql" }}
        - name: RPI_OperationalDatabaseType
          value: "PostgreSQL"
        {{- end }}
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-node-manager:{{ .Values.global.image_tag }}
        imagePullPolicy: Always
        name: node-manager
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

---
{{- if eq .Values.global.cloud "google" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-nodemanager
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-nodemanager
spec:
  replicas: {{ .Values.replicas.nodemanager }}
  selector:
    matchLabels:
      app: rpi-nodemanager
  template:
    metadata:
      labels:
        app: rpi-nodemanager
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: redpoint-rpi
      containers:
      - env:
        - name: RPIClient__applicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: Logging__Database__LogLevel__Default
          value: "Error"
        {{- if eq .Values.databases.type "postgresql" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: postgresql-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: postgresql-secrets
        {{- end }}
        {{- if eq .Values.databases.type "azuresqlserver" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sqlserver-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sqlserver-secrets
        {{- end }}
        {{- if eq .Values.databases.type "amazonrdssql" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sqlserver-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sqlserver-secrets
        {{- end }}
        {{- if eq .Values.databases.type "googlecloudsql" }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sqlserver-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sqlserver-secrets
        {{- end }}
        - name: RealtimeAPIAddressOverride
          value: "http://rpi-realtimeapi"
        - name: Authentication__EnableRPIAuthentication
          value: "true"
        - name: DisableHttpRedirect
          value: "true"
        {{- if eq .Values.databases.type "postgresql" }}
        - name: RPI_OperationalDatabaseType
          value: "PostgreSQL"
        {{- end }}
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-node-manager:{{ .Values.global.image_tag }}
        imagePullPolicy: Always
        name: node-manager
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}