apiVersion: v1
kind: Service
metadata:
  name: rpi-realtimeapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-realtimeapi
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-realtimeapi

---
{{- if eq .Values.global.cloud "demo" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-realtimeapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-realtimeapi
spec:
  replicas: {{ .Values.replicas.realtime }}
  selector:
    matchLabels:
      app: rpi-realtimeapi
  template:
    metadata:
      labels:
        app: rpi-realtimeapi
    spec:
      serviceAccountName: sa-redpoint-rpi
      containers:
        - name: rpi-realtimeapi
          image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-realtime-plus-agent:{{ .Values.global.image_tag }}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web-port
            protocol: TCP
          env:
          - name: CONNECTIONSTRINGS__LOGGINGDATABASE
            valueFrom:
              secretKeyRef:
                key: ConnectionStrings__LoggingDatabase
                name: database-secrets
          - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
            valueFrom:
              secretKeyRef:
                key: ConnectionStrings__OperationalDatabase
                name: database-secrets
          - name: RealtimeAPIConfiguration__AppSettings__PluginAssemblyPath
            value: ""
          volumeMounts:
            - name: rpi-realtimeapi
              mountPath: /app/appsettings
      volumes:
        - name: rpi-realtimeapi
          configMap:
            name: rpi-realtimeapi
{{- end }}

---
{{- if eq .Values.global.cloud "amazon" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-realtimeapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-realtimeapi
spec:
  replicas: {{ .Values.replicas.realtime }}
  selector:
    matchLabels:
      app: rpi-realtimeapi
  template:
    metadata:
      labels:
        app: rpi-realtimeapi
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: sa-redpoint-rpi
      containers:
        - name: rpi-realtimeapi
          image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-realtime-plus-agent:{{ .Values.global.image_tag }}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web-port
            protocol: TCP
          env:
          - name: CONNECTIONSTRINGS__LOGGINGDATABASE
            valueFrom:
              secretKeyRef:
                key: ConnectionStrings__LoggingDatabase
                name: database-secrets
          - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
            valueFrom:
              secretKeyRef:
                key: ConnectionStrings__OperationalDatabase
                name: database-secrets
          - name: RealtimeAPIConfiguration__AppSettings__PluginAssemblyPath
            value: ""
          volumeMounts:
            - name: rpi-realtimeapi
              mountPath: /app/appsettings
      volumes:
        - name: rpi-realtimeapi
          configMap:
            name: rpi-realtimeapi
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

---
{{- if eq .Values.global.cloud "azure" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-realtimeapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-realtimeapi
spec:
  replicas: {{ .Values.replicas.realtime }}
  selector:
    matchLabels:
      app: rpi-realtimeapi
  template:
    metadata:
      labels:
        app: rpi-realtimeapi
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: sa-redpoint-rpi
      containers:
        - name: rpi-realtimeapi
          image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-realtime-plus-agent:{{ .Values.global.image_tag }}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web-port
            protocol: TCP
          env:
          - name: CONNECTIONSTRINGS__LOGGINGDATABASE
            valueFrom:
              secretKeyRef:
                key: ConnectionStrings__LoggingDatabase
                name: database-secrets
          - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
            valueFrom:
              secretKeyRef:
                key: ConnectionStrings__OperationalDatabase
                name: database-secrets
          - name: RealtimeAPIConfiguration__AppSettings__PluginAssemblyPath
            value: ""
          volumeMounts:
            - name: rpi-realtimeapi
              mountPath: /app/appsettings
      volumes:
        - name: rpi-realtimeapi
          configMap:
            name: rpi-realtimeapi
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

---
{{- if eq .Values.global.cloud "google" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-realtimeapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-realtimeapi
spec:
  replicas: {{ .Values.replicas.realtime }}
  selector:
    matchLabels:
      app: rpi-realtimeapi
  template:
    metadata:
      labels:
        app: rpi-realtimeapi
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: sa-redpoint-rpi
      containers:
        - name: rpi-realtimeapi
          image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-realtime-plus-agent:{{ .Values.global.image_tag }}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web-port
            protocol: TCP
          env:
          - name: CONNECTIONSTRINGS__LOGGINGDATABASE
            valueFrom:
              secretKeyRef:
                key: ConnectionStrings__LoggingDatabase
                name: database-secrets
          - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
            valueFrom:
              secretKeyRef:
                key: ConnectionStrings__OperationalDatabase
                name: database-secrets
          - name: RealtimeAPIConfiguration__AppSettings__PluginAssemblyPath
            value: ""
          volumeMounts:
            - name: rpi-realtimeapi
              mountPath: /app/appsettings
      volumes:
        - name: rpi-realtimeapi
          configMap:
            name: rpi-realtimeapi
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}