{{- if eq .Values.global.deploymentType "client" }}
apiVersion: v1
kind: Secret
metadata:
  name: sql-rpiops-connstring
  namespace: {{ .Values.global.namespace }}
data:
  ConnectionStrings__LoggingDatabase: {{ .Values.appsettings.configeditor.sqlServer.ConnectionStrings_LoggingDatabase | b64enc }} 
  ConnectionStrings__OperationalDatabase: {{ .Values.appsettings.configeditor.sqlServer.ConnectionStrings_OperationalDatabase | b64enc }}
type: Opaque
{{- end }}

---
{{- if eq .Values.appsettings.configeditor.sqlServer.type "demo" }}
apiVersion: v1
kind: Secret
metadata:
  name: sql-rpiops-connstring
  namespace: {{ .Values.global.namespace }}
data:
  ConnectionStrings__LoggingDatabase: {{ .Values.appsettings.configeditor.sqlServer.ConnectionStrings_LoggingDatabase | b64enc }} 
  ConnectionStrings__OperationalDatabase: {{ .Values.appsettings.configeditor.sqlServer.ConnectionStrings_OperationalDatabase | b64enc }}
type: Opaque
{{- end }}

---
{{- if eq .Values.global.deploymentType "internal" }}
apiVersion: v1
kind: Secret
metadata:
  name: sql-rpiops-connstring
  namespace: {{ .Values.global.namespace }}
data:
  ConnectionStrings__LoggingDatabase: {{ .Values.appsettings.configeditor.sqlServer.ConnectionStrings_LoggingDatabase | b64enc }} 
  ConnectionStrings__OperationalDatabase: {{ .Values.appsettings.configeditor.sqlServer.ConnectionStrings_OperationalDatabase | b64enc }}
type: Opaque
{{- end }}
