---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rpi-interactionapi
  namespace: {{ .Values.global.namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: rpi-interactionapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-interactionapi
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-interactionapi
    
---
{{- if eq .Values.global.deploymentType "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-interactionapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.application.name }}
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: rpi-interactionapi
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-interactionapi
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      imagePullSecrets:
        - name: docker-io
      serviceAccountName: sa-rpi-interactionapi
      {{- if .Values.mssql.enabled }}
      initContainers:
      - name: wait-for-mssql
        image: busybox:1.33.1
        command:
        - /bin/sh
        - -c
        - >
          until nc -zv sql-rpi-ops 1433;
          do echo "waiting for mssql" && sleep 2;
          done
      {{- end }}
      containers:
      - env:
        - name: RPIClient__HelpStartPageURL
          value: "https://{{ .Values.ingress.hosts.helpdocs }}"
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: RPIClient__AllowSavingLoginDetails
          value: "true"
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir
        - name: RPIClient__AlwaysShowClientsAtLogin
          value: "true"
        - name: RPIClient__ApplicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: Logging__Database__LogLevel__Default
          value: "Error"
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sql-rpiops-connstring
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sql-rpiops-connstring
        image: rpspeastus2acr.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-api:{{ .Values.global.image_tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: interaction-api
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-interactionapi
            mountPath: /app/appsettings
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
      hostname: redpoint-interaction-api
      volumes:
        - name: rpi-interactionapi
          configMap:
            name: cm-rpi-interactionapi
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: rpifileoutputdir
{{- end }}


---
{{- if eq .Values.global.deploymentType "client" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-interactionapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.application.name }}
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: rpi-interactionapi
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-interactionapi
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      imagePullSecrets:
        - name: docker-io
      serviceAccountName: sa-rpi-interactionapi
      containers:
      - env:
        - name: RPIClient__HelpStartPageURL
          value: "https://{{ .Values.ingress.hosts.helpdocs }}"
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: RPIClient__AllowSavingLoginDetails
          value: "true"
        - name: RPIClient__AlwaysShowClientsAtLogin
          value: "true"
        - name: RPIClient__ApplicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir 
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: Logging__Database__LogLevel__Default
          value: "Error"
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sql-rpiops-connstring
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sql-rpiops-connstring
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-api:{{ .Values.global.image_tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: interaction-api
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-interactionapi
            mountPath: /app/appsettings
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
      hostname: redpoint-interaction-api
      volumes:
        - name: rpi-interactionapi
          configMap:
            name: cm-rpi-interactionapi
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: {{ .Values.global.namespace }}
{{- end }}