{{- if eq .Values.global.cloudProvider "azure" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.global.namespace }}
provisioner: file.csi.azure.com 
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Premium_LRS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.global.namespace }}
  resources:
    requests:
      storage: "100"
{{- end }}


{{- if eq .Values.global.cloudProvider "google" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
spec:
  capacity:
    storage: {{ .Values.storage.google.capacity }}
  accessModes:
  - ReadWriteMany
  nfs:
    path: {{ .Values.storage.google.path }}
    server: {{ .Values.storage.google.server | quote }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: {{ .Values.storage.google.share_name }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.google.capacity }}
{{- end }}

---
{{- if eq .Values.global.cloudProvider "amazon" }}
apiVersion: v1
kind: PersistentVolume
metadata:
name: rpi-rpifileoutputdir
spec:
capacity:
storage: {{ .Values.appsettings.storage.size.rpi_output_directory }}
accessModes:
- ReadWriteMany
persistentVolumeReclaimPolicy: Retain
mountOptions:
- dir_mode=0777
- file_mode=0777
- vers=3.0
csi:
driver: {{ .Values.appsettings.storage.class.amazon.provisioner }}
readOnly: false
volumeHandle: {{ .Values.appsettings.storage.class.amazon.volumeHandle }} 

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rpi-rpifileoutputdir
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.appsettings.storage.size.rpi_output_directory }}
  volumeName: rpi-rpifileoutputdir
  storageClassName: smb
{{- end }}