{{- if .Values.realtimeapi.cacheProvider.redis.internal }}
apiVersion: v1
kind: Service
metadata:
  name: realtime-rediscache
  namespace: {{ .Release.Namespace }}
  labels:
    app: realtime-rediscache
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 6379
  selector:
    app: realtime-rediscache

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-rediscache
  namespace: {{ .Release.Namespace }}
  labels:
    app: realtime-rediscache
spec:
  replicas: {{ .Values.realtimeapi.cacheProvider.redis.replicas }}
  selector:
    matchLabels:
      app: realtime-rediscache
  template:
    metadata:
      labels:
        app: realtime-rediscache
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: realtime-rediscache
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
      {{- end }}
      containers:
      - name: realtime-rediscache
        image: {{ .Values.global.deployment.images.rediscache }}:{{ .Values.global.deployment.images.tag }}
        imagePullPolicy: {{  .Values.global.deployment.images.imagePullPolicy }}
        ports:
        - containerPort: 6379
          name: web-port
          protocol: TCP
        {{- if .Values.securityContext.enabled }}
        securityContext:
          privileged: {{ .Values.securityContext.privileged }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          capabilities:
            drop:
            {{- range .Values.securityContext.capabilities.drop }}
              - {{ . }}
            {{- end }}
        {{- end }}
        {{- if .Values.realtimeapi.cacheProvider.redis.resources.enabled }}
        resources:
          {{- if .Values.realtimeapi.cacheProvider.redis.resources.limits }}
          limits:
            {{- if .Values.realtimeapi.cacheProvider.redis.resources.limits.cpu }}
            cpu: {{ .Values.realtimeapi.cacheProvider.redis.resources.limits.cpu }}
            {{- end }}
            {{- if .Values.realtimeapi.cacheProvider.redis.resources.limits.memory }}
            memory: {{ .Values.realtimeapi.cacheProvider.redis.resources.limits.memory }}
            {{- end }}
          {{- end }}
          {{- if .Values.realtimeapi.cacheProvider.redis.resources.requests }}
          requests:
            {{- if .Values.realtimeapi.cacheProvider.redis.resources.requests.cpu }}
            cpu: {{ .Values.realtimeapi.cacheProvider.redis.resources.requests.cpu }}
            {{- end }}
            {{- if .Values.realtimeapi.cacheProvider.redis.resources.requests.memory }}
            memory: {{ .Values.realtimeapi.cacheProvider.redis.resources.requests.memory }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
      {{- end }}
      {{- if .Values.tolerations.enabled }}
      tolerations:
        - effect: NoSchedule
          key: {{ .Values.nodeSelector.key }}
          operator: Equal
          value: {{ .Values.nodeSelector.value }}
      {{- end }}
{{- end }}