---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rpi-execution-service
  namespace: {{ .Values.global.namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: rpi-execution-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-execution-service
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-execution-service

---
{{- if eq .Values.global.deploymentType "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-execution-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-execution-service
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: rpi-execution-service
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-execution-service
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      imagePullSecrets:
        - name: docker-io
      serviceAccountName: sa-rpi-execution-service
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: RPIClient__ApplicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: Logging__Database__LogLevel__Default
          value: "Error"     
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir 
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sql-rpiops-connstring
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sql-rpiops-connstring
        image: rpspeastus2acr.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-execution-service:{{ .Values.global.image_tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: execution-service
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-execution-service
            mountPath: /app/appsettings
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
      volumes:
        - name: rpi-execution-service
          configMap:
            name: cm-rpi-execution-service
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: rpifileoutputdir
      nodeSelector:
        pool: rpinternal
      tolerations:
        - effect: NoSchedule
          key: pool
          operator: Equal
          value: rpinternal
{{- end }}

---

{{- if eq .Values.global.deploymentType "client" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-execution-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-execution-service
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: rpi-execution-service
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-execution-service
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: sa-rpi-execution-service
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: RPIClient__ApplicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir
        - name: Logging__Database__LogLevel__Default
          value: "Error"     
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sql-rpiops-connstring
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sql-rpiops-connstring
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-execution-service:{{ .Values.global.image_tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: execution-service
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-execution-service
            mountPath: /app/appsettings
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
      volumes:
        - name: rpi-execution-service
          configMap:
            name: cm-rpi-execution-service
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: {{ .Values.global.namespace }}
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}