{{- if .Values.realtimeapi.cacheProvider.redis.internal }}
apiVersion: v1
kind: Service
metadata:
  name: realtime-rediscache
  namespace: {{ .Release.Namespace }}
  labels:
    app: realtime-rediscache
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 6379
  selector:
    app: realtime-rediscache

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-rediscache
  namespace: {{ .Release.Namespace }}
  labels:
    app: realtime-rediscache
spec:
  replicas: {{ .Values.realtimeapi.cacheProvider.redis.replicas }}
  selector:
    matchLabels:
      app: realtime-rediscache
  template:
    metadata:
      labels:
        app: realtime-rediscache
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: realtime-rediscache
      containers:
      - name: realtime-rediscache
        image: {{ .Values.global.deployment.images.rediscache }}:{{ .Values.global.deployment.images.tag }}
        imagePullPolicy: {{  .Values.global.deployment.images.imagePullPolicy }}
        ports:
        - containerPort: 6379
          name: web-port
          protocol: TCP
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
      {{- end }}
      {{- if .Values.tolerations.enabled }}
      tolerations:
        - effect: NoSchedule
          key: {{ .Values.nodeSelector.key }}
          operator: Equal
          value: {{ .Values.nodeSelector.value }}
      {{- end }}
{{- end }}