---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rpi-config-editor
  namespace: {{ .Values.global.namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: rpi-config-editor
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-config-editor
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-config-editor

---
{{- if eq .Values.global.deploymentType "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-config-editor
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-config-editor
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: rpi-config-editor
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-config-editor
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      serviceAccountName: sa-rpi-config-editor
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ClusterEnvironment__OperationalDatabase__ConnectionSettings__DatabaseType
          valueFrom:
            secretKeyRef:
              key: DatabaseType
              name: sql-config-editor
        - name: ClusterEnvironment__OperationalDatabase__ConnectionSettings__Server
          valueFrom:
            secretKeyRef:
              key: Server
              name: sql-config-editor
        - name: ClusterEnvironment__OperationalDatabase__ConnectionSettings__Username
          valueFrom:
            secretKeyRef:
              key: Username
              name: sql-config-editor
        - name: ClusterEnvironment__OperationalDatabase__ConnectionSettings__Password
          valueFrom:
            secretKeyRef:
              key: Password
              name: sql-config-editor
        image: rpspeastus2acr.azurecr.io/docker/redpointinteraction/7-2/prod/redpoint-interaction-configuration-editor:{{ .Values.global.image_tag_internal }}
        imagePullPolicy: Always
        name: config-editor
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-config-editor
            mountPath: /app/appsettings
      volumes:
        - name: rpi-config-editor
          configMap:
            name: rpi-config-editor
      nodeSelector:
        pool: rgoc-eus2
      tolerations:
        - effect: NoSchedule
          key: pool
          operator: Equal
          value: rgoc-eus2
{{- end }}

---
{{- if eq .Values.global.deploymentType "client" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-config-editor
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-config-editor
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: rpi-config-editor
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-config-editor
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: sa-rpi-config-editor
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ClusterEnvironment__OperationalDatabase__ConnectionSettings__DatabaseType
          valueFrom:
            secretKeyRef:
              key: DatabaseType
              name: sql-config-editor
        - name: ClusterEnvironment__OperationalDatabase__ConnectionSettings__Server
          valueFrom:
            secretKeyRef:
              key: Server
              name: sql-config-editor
        - name: ClusterEnvironment__OperationalDatabase__ConnectionSettings__Username
          valueFrom:
            secretKeyRef:
              key: Username
              name: sql-config-editor
        - name: ClusterEnvironment__OperationalDatabase__ConnectionSettings__Password
          valueFrom:
            secretKeyRef:
              key: Password
              name: sql-config-editor
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-configuration-editor:{{ .Values.global.image_tag_client }}
        imagePullPolicy: Always
        name: config-editor
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-config-editor
            mountPath: /app/appsettings
      volumes:
        - name: rpi-config-editor
          configMap:
            name: rpi-config-editor
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}