---
apiVersion: v1
kind: Secret
metadata:
  name: sql-rpiops-connstring
  namespace: {{ .Values.global.namespace }}
data:
  ConnectionStrings__LoggingDatabase: {{ .Values.appsettings.configeditor.ConnectionSettings.ConnectionStrings_LoggingDatabase | b64enc }} 
  ConnectionStrings__OperationalDatabase: {{ .Values.appsettings.configeditor.ConnectionSettings.ConnectionStrings_OperationalDatabase | b64enc }}
type: Opaque
