{{- if eq .Values.global.deploymentType "client" }}
apiVersion: v1
kind: Secret
metadata:
  name: sql-rpiops-connstring
  namespace: {{ .Values.global.namespace }}
data:
  ConnectionStrings__LoggingDatabase: {{ .Values.appsettings.configeditor.ConnectionSettings.ConnectionStrings_LoggingDatabase | b64enc }} 
  ConnectionStrings__OperationalDatabase: {{ .Values.appsettings.configeditor.ConnectionSettings.ConnectionStrings_OperationalDatabase | b64enc }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: sql-config-editor
  namespace: {{ .Values.global.namespace }}
data:
  DatabaseType: {{ .Values.appsettings.configeditor.ConnectionSettings.DatabaseType | b64enc }}
  Password: {{ .Values.appsettings.configeditor.ConnectionSettings.Password | b64enc }}
  Server: {{ .Values.appsettings.configeditor.ConnectionSettings.Server | b64enc }}
  Username: {{ .Values.appsettings.configeditor.ConnectionSettings.Username | b64enc }}
type: Opaque
{{- end }}