---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rpi-interactionapi
  namespace: {{ .Values.global.namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: rpi-interactionapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-interactionapi
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-interactionapi
    
---
{{- if eq .Values.global.deploymentType "internal" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-interactionapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.application.name }}
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: rpi-interactionapi
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-interactionapi
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      serviceAccountName: sa-rpi-interactionapi
      containers:
      - env:
        - name: RPIClient__HelpStartPageURL
          value: "https://{{ .Values.ingress.hosts.helpdocs }}"
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: RPI__SMTP__EmailSenderAddress
          value: {{ .Values.SMTPSettings.SMTP_SenderAddress | quote }}
        - name: RPI__SMTP__Address
          value: {{ .Values.SMTPSettings.SMTP_Address | quote }}
        - name: RPI__SMTP__Port
          value: {{ .Values.SMTPSettings.SMTP_Port | quote }}
        - name: RPI__SMTP__EnableSSL
          value: "true"
        - name: RPI__SMTP__UseCredentials
          value: "true"
        - name: RPI__SMTP__Username
          value: {{ .Values.SMTPSettings.SMTP_Username | quote }}
        - name: RPI__SMTP__Password
          value: {{ .Values.SMTPSettings.SMTP_Password | quote }}
        - name: Mercury__Address
          value: {{ .Values.MercurySettings.Mercury_Address }}
        - name: Mercury__Username
          value: {{ .Values.MercurySettings.Mercury_Username }}
        - name: Mercury__Password
          value: {{ .Values.MercurySettings.Mercury_Password }}
        - name: RPIClient__AllowSavingLoginDetails
          value: "true"
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir
        - name: RPIClient__AlwaysShowClientsAtLogin
          value: "true"
        - name: RPIClient__ApplicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: Logging__Database__LogLevel__Default
          value: "Error"
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sql-rpiops-connstring
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sql-rpiops-connstring
        image: rpspeastus2acr.azurecr.io/docker/redpointinteraction/7-2/prod/redpoint-interaction-api:{{ .Values.global.image_tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: interaction-api
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-interactionapi
            mountPath: /app/appsettings
          {{- if .Values.appsettings.storage.enabled }}
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
          {{- end }}
      hostname: redpoint-interaction-api
      volumes:
        - name: rpi-interactionapi
          configMap:
            name: cm-rpi-interactionapi
        {{- if .Values.appsettings.storage.enabled }}
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: {{ .Values.appsettings.storage.persistentVolumeClaim }}
        {{- end }}
      nodeSelector:
        pool: rgoc-eus2
      tolerations:
        - effect: NoSchedule
          key: pool
          operator: Equal
          value: rgoc-eus2
{{- end }}


---
{{- if eq .Values.global.deploymentType "client" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-interactionapi
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.application.name }}
    env: {{ .Values.global.application.environment }}
    version: {{ .Values.global.application.version | quote }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: rpi-interactionapi
      env: {{ .Values.global.application.environment }}
      version: {{ .Values.global.application.version | quote }}
  template:
    metadata:
      labels:
        app: rpi-interactionapi
        env: {{ .Values.global.application.environment }}
        version: {{ .Values.global.application.version | quote }}
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: sa-rpi-interactionapi
      containers:
      - env:
        - name: RPIClient__HelpStartPageURL
          value: "https://{{ .Values.ingress.hosts.helpdocs }}"
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: RPI__SMTP__EmailSenderAddress
          value: {{ .Values.SMTPSettings.SMTP_SenderAddress | quote }}
        - name: RPI__SMTP__Address
          value: {{ .Values.SMTPSettings.SMTP_Address | quote }}
        - name: RPI__SMTP__Port
          value: {{ .Values.SMTPSettings.SMTP_Port | quote }}
        - name: RPI__SMTP__EnableSSL
          value: "true"
        - name: RPI__SMTP__UseCredentials
          value: "true"
        - name: RPI__SMTP__Username
          value: {{ .Values.SMTPSettings.SMTP_Username | quote }}
        - name: RPI__SMTP__Password
          value: {{ .Values.SMTPSettings.SMTP_Password | quote }}
        - name: Mercury__Address
          value: {{ .Values.MercurySettings.Mercury_Address }}
        - name: Mercury__Username
          value: {{ .Values.MercurySettings.Mercury_Username }}
        - name: Mercury__Password
          value: {{ .Values.MercurySettings.Mercury_Password }}
        - name: RPIClient__AllowSavingLoginDetails
          value: "true"
        - name: RPIClient__AlwaysShowClientsAtLogin
          value: "true"
        - name: RPIClient__ApplicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir 
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: Logging__Database__LogLevel__Default
          value: "Error"
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: sql-rpiops-connstring
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: sql-rpiops-connstring
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-api:{{ .Values.global.image_tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        name: interaction-api
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-interactionapi
            mountPath: /app/appsettings
          {{- if .Values.appsettings.storage.enabled }}
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
          {{- end }}
      hostname: redpoint-interaction-api
      volumes:
        - name: rpi-interactionapi
          configMap:
            name: cm-rpi-interactionapi
        {{- if .Values.appsettings.storage.enabled }}
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: {{ .Values.appsettings.storage.persistentVolumeClaim }}
        {{- end }}
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}