{{- if .Values.integrationapi.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.integrationapi.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-integrationapi
  {{- if eq .Values.global.deployment.platform "azure" }}
  {{- if .Values.cloudIdentity.enabled }}
  {{- if eq .Values.cloudIdentity.azureSettings.credentialsType "workloadIdentity" }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.cloudIdentity.azureSettings.managedIdentityClientId }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.global.deployment.platform "google" }}
  {{- if .Values.cloudIdentity.enabled }}
  {{- if eq .Values.cloudIdentity.azureSettings.credentialsType "workloadIdentity" }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.cloudIdentity.googleSettings.serviceAccountEmail | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: rpi-integrationapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-integrationapi
spec:
  ports:
  - name: http
    port: {{ .Values.services.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-integrationapi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-integrationapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-integrationapi
    {{- with .Values.integrationapi.customLabels }}
    {{- toYaml . | nindent 4 }} 
    {{- end }}
spec:
  {{- if not .Values.integrationapi.autoscaling.enabled }}
  replicas: {{ .Values.integrationapi.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: rpi-integrationapi
  template:
    metadata:
      labels:
        app: rpi-integrationapi
        {{- with .Values.integrationapi.customLabels }}
        {{- toYaml . | nindent 8 }} 
        {{- end }}
        {{- if eq .Values.global.deployment.platform "azure" }}
        {{- if eq .Values.cloudIdentity.azureSettings.credentialsType "workloadIdentity" }}
        azure.workload.identity/use: "true"
        {{- end }}
        {{- end }}
      annotations:
        {{- with .Values.integrationapi.customAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.integrationapi.customMetrics.enabled }}
        prometheus.io/scrape: {{ .Values.integrationapi.customMetrics.prometheus_scrape | quote }}
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
        {{- end }}
    spec:
      {{- if .Values.global.deployment.images.imagePullSecret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.global.deployment.images.imagePullSecret.name }}
      {{- end }}
      serviceAccountName: {{ .Values.integrationapi.serviceAccount.name }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
      containers:
      - env:
        - name: Logging__LogLevel__Default
          value: {{ .Values.integrationapi.logging.logLevel | quote }}
        - name: Authentication__EnableRPIAuthentication
          value: {{ .Values.integrationapi.enableRPIAuthentication | quote }}
        - name: Authentication__RPIAuthentication__AuthorizationHost
          value: "https://{{ .Values.ingress.hosts.integration }}.{{ .Values.ingress.domain }}"
        - name: Authentication__RPIAuthentication__AuthMetaHttpHost
          value: "http://rpi-integrationapi"
        - name: Authentication__RPIAuthentication__EnableTransportSecurityRequirement
          value: "false"
        - name: EnableSwagger
          value: {{ .Values.integrationapi.enableSwagger | quote }}
        {{- if .Values.cloudIdentity.enabled }}
        {{- if eq .Values.cloudIdentity.provider "Azure" }}
        {{- if eq .Values.cloudIdentity.azureSettings.credentialsType "workloadIdentity" }}
        - name: CloudIdentity__Azure__CredentialType
          value: "AzureIdentity"
        - name: CloudIdentity__Azure__UseADTokenForDatabaseConnection
          value: {{ .Values.cloudIdentity.azureSettings.UseADTokenForDatabaseConnection | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.cloudIdentity.secretsManagement.enabled }}
        - name: KeyVault__Provider
          value: "Azure"
        - name: KeyVault__UseForAppSettings
          value: {{ .Values.cloudIdentity.secretsManagement.UseForAppSettings | quote }}
        - name: KeyVault__UseForConfigPasswords
          value: {{ .Values.cloudIdentity.secretsManagement.UseForConfigPasswords | quote }}
        - name: KeyVault__AzureSettings__VaultURI
          value: {{ .Values.cloudIdentity.azureSettings.vaultUri | quote }}
        - name: KeyVault__AzureSettings__AppSettingsVaultURI
          value: {{ .Values.cloudIdentity.azureSettings.appSettingsVaultUri | quote }}
        - name: KeyVault__AzureSettings__ConfigurationReloadIntervalSeconds
          value: {{ .Values.cloudIdentity.secretsManagement.ConfigurationReloadIntervalSeconds | quote }}
        {{- end }}
        {{- if .Values.cloudIdentity.enabled }}
        {{- if eq .Values.cloudIdentity.provider "Google" }}
        {{- if eq .Values.cloudIdentity.googleSettings.credentialsType "serviceAccount" }}
        - name: CloudIdentity__Google_ProjectId
          value: {{ .Values.cloudIdentity.googleSettings.projectId | quote }}
        - name: GOOGLE_APPLICATION_CREDENTIALS 
          value: "/app/google-creds/{{ .Values.cloudIdentity.googleSettings.serviceAccountName }}.json"
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.cloudIdentity.secretsManagement.enabled }}
        - name: KeyVault__Provider
          value: "Google"
        - name: KeyVault__UseForAppSettings
          value: {{ .Values.cloudIdentity.secretsManagement.UseForAppSettings | quote }}
        - name: KeyVault__UseForConfigPasswords
          value: {{ .Values.cloudIdentity.secretsManagement.UseForConfigPasswords | quote }}
        {{- end }}
        {{- if .Values.cloudIdentity.enabled }}
        {{- if eq .Values.cloudIdentity.provider "Amazon" }}
        {{- if eq .Values.cloudIdentity.secretsManagement.secretsProvider "keyvault" }}
        - name: CloudIdentity__Amazon__AccessKeyId
          value: {{ .Values.cloudIdentity.amazonSettings.accessKeyId | quote }}
        - name: CloudIdentity__Amazon__SecretAccessKey
          value: {{ .Values.cloudIdentity.amazonSettings.secretAccessKey | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.cloudIdentity.secretsManagement.enabled }}
        - name: KeyVault__Provider
          value: "Amazon"
        - name: KeyVault__UseForAppSettings
          value: {{ .Values.cloudIdentity.secretsManagement.UseForAppSettings | quote }}
        - name: KeyVault__UseForConfigPasswords
          value: {{ .Values.cloudIdentity.secretsManagement.UseForConfigPasswords | quote }}
        {{- end }}
        {{- if .Values.OpenIdProviders.enabled }}
        - name: Authentication__OpenIdProviders__0__Name
          value: {{ .Values.OpenIdProviders.Name | quote }}
        - name: Authentication__OpenIdProviders__0__AuthorizationHost
          value: {{ .Values.OpenIdProviders.AuthorizationHost | quote }}
        - name: Authentication__OpenIdProviders__0__ClientID
          value: {{ .Values.OpenIdProviders.ClientID | quote }}
        - name: Authentication__OpenIdProviders__0__Audience
          value: {{ .Values.OpenIdProviders.Audience | quote }}
        - name: Authentication__OpenIdProviders__0__RedirectURL
          value: {{ .Values.OpenIdProviders.RedirectURL | quote }}
        - name: Authentication__OpenIdProviders__0__EnableRefreshTokens
          value: {{ .Values.OpenIdProviders.EnableRefreshTokens | quote }}
        - name: Authentication__OpenIdProviders__0__LogoutIdTokenParameter
          value: {{ .Values.OpenIdProviders.LogoutIdTokenParameter | quote }}
        - name: Authentication__OpenIdProviders__0__ValidateIssuer
          value: {{ .Values.OpenIdProviders.ValidateIssuer | quote }}
        - name: Authentication__OpenIdProviders__0__ValidateAudience
          value: {{ .Values.OpenIdProviders.ValidateAudience | quote }}
        {{- end }}
        {{- if eq .Values.databases.operational.provider "sqlserver" }}
        {{- if eq .Values.cloudIdentity.secretsManagement.secretsProvider "kubernetes" }}
        {{- if .Values.cloudIdentity.secretsManagement.autoCreateSecrets }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionString_Logging_Database
              name: redpoint-rpi-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionString_Operations_Database
              name: redpoint-rpi-secrets
        {{- end }}
        {{- end }}   
        {{- end }}
        {{- if eq .Values.databases.operational.provider "sqlserveronvm" }}
        {{- if eq .Values.cloudIdentity.secretsManagement.secretsProvider "kubernetes" }}
        {{- if .Values.cloudIdentity.secretsManagement.autoCreateSecrets }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionString_Logging_Database
              name: redpoint-rpi-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionString_Operations_Database
              name: redpoint-rpi-secrets
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if eq .Values.databases.operational.provider "postgresql" }}
        {{- if eq .Values.cloudIdentity.secretsManagement.secretsProvider "kubernetes" }}
        {{- if .Values.cloudIdentity.secretsManagement.autoCreateSecrets }}
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionString_Logging_Database
              name: redpoint-rpi-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionString_Operations_Database
              name: redpoint-rpi-secrets
        - name: RPI_OperationalDatabaseType
          value: "PostgreSQL"
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if .Values.storage.enabled }}
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir
        {{- end }}
        {{- if .Values.redpointAI.enabled }}
        {{- if .Values.cloudIdentity.secretsManagement.autoCreateSecrets }}
        - name: RPI__NLP__ApiKey
          valueFrom:
            secretKeyRef:
              key:  RPI_NLP_API_KEY
              name: redpoint-rpi-secrets
        - name: RPI__NLP__SearchKey
          valueFrom:
            secretKeyRef:
              key:  RPI_NLP_SEARCH_KEY
              name: redpoint-rpi-secrets
        - name: RPI__NLP__Model__ConnectionString
          valueFrom:
            secretKeyRef:
              key:  RPI_NLP_MODEL_CONNECTION_STRING
              name: redpoint-rpi-secrets
        {{- end }}
        {{- end }}
        {{- if .Values.redpointAI.enabled }}
        - name: RPI__NLP__ApiBase
          value: {{ .Values.redpointAI.naturalLanguage.ApiBase | quote }} 
        - name: RPI__NLP__ApiVersion
          value: {{ .Values.redpointAI.naturalLanguage.ApiVersion | quote }}
        - name: RPI__NLP__ChatGptEngine
          value: {{ .Values.redpointAI.naturalLanguage.ChatGptEngine | quote }} 
        - name: RPI__NLP__ChatGptTemp
          value: {{ .Values.redpointAI.naturalLanguage.ChatGptTemp | quote }}
        - name: RPI__NLP__SearchEndpoint
          value: {{ .Values.redpointAI.cognitiveSearch.SearchEndpoint | quote }} 
        - name: RPI__NLP__Model__VectorSearchProfile
          value: {{ .Values.redpointAI.cognitiveSearch.VectorSearchProfile | quote }}
        - name: RPI__NLP__Model__VectorSearchConfig
          value: {{ .Values.redpointAI.cognitiveSearch.VectorSearchConfig | quote }}
        - name: RPI__NLP__EmbeddingsModel
          value: {{ .Values.redpointAI.modelStorage.EmbeddingsModel | quote }}
        - name: RPI__NLP__Model__ModelDimensions
          value: {{ .Values.redpointAI.modelStorage.ModelDimensions | quote }}
        - name: RPI__NLP__Model__ContainerName
          value: {{ .Values.redpointAI.modelStorage.ContainerName | quote }}
        - name: RPI__NLP__Model__BlobFolder
          value: {{ .Values.redpointAI.modelStorage.BlobFolder | quote }}
        {{- end }}
        image: {{ .Values.global.deployment.images.integrationapi }}:{{ .Values.global.deployment.images.tag }}
        imagePullPolicy: {{  .Values.global.deployment.images.imagePullPolicy }}
        name: integration-api
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.integrationapi.resources.limits.cpu }}
            memory: {{ .Values.integrationapi.resources.limits.memory }}
          requests:
            cpu: {{ .Values.integrationapi.resources.requests.cpu }}
            memory: {{ .Values.integrationapi.resources.requests.memory }}
        {{- if .Values.storage.enabled }}
        volumeMounts:
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
        {{- end }}
      {{- if .Values.storage.enabled }}
      volumes:
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: {{ .Values.storage.persistentVolumeClaim }}
      {{- end }}
      {{- if .Values.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
      {{- end }}
      {{- if .Values.tolerations.enabled }}
      tolerations:
        - effect: NoSchedule
          key: {{ .Values.nodeSelector.key }}
          operator: Equal
          value: {{ .Values.nodeSelector.value }}
      {{- end }}

