apiVersion: v1
kind: Service
metadata:
  name: rpi-executionservice
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-executionservice
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-executionservice

---
{{- if eq .Values.global.cloud "demo" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-executionservice
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-executionservice
spec:
  replicas: {{ .Values.replicas.executionservice }}
  selector:
    matchLabels:
      app: rpi-executionservice
  template:
    metadata:
      labels:
        app: rpi-executionservice
    spec:
      serviceAccountName: sa-rpi-executionservice
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: RPI__SMTP__EmailSenderAddress
          value: {{ .Values.SMTPSettings.SMTP_SenderAddress | quote }}
        - name: RPI__SMTP__Address
          value: {{ .Values.SMTPSettings.SMTP_Address | quote }}
        - name: RPI__SMTP__Port
          value: {{ .Values.SMTPSettings.SMTP_Port | quote }}
        - name: RPI__SMTP__EnableSSL
          value: "true"
        - name: RPI__SMTP__UseCredentials
          value: "true"
        - name: RPI__SMTP__Username
          value: {{ .Values.SMTPSettings.SMTP_Username | quote }}
        - name: RPI__SMTP__Password
          value: {{ .Values.SMTPSettings.SMTP_Password | quote }}
        - name: RPIExecution__MaxThreadsPerExecutionService
          value: {{ .Values.executionservice.RPIExecution_MaxThreadsPerExecutionService | quote }}
        - name: RPIExecution__QueueListener__IsEnabled
          value: {{ .Values.executionservice.RPIExecution__QueueListener__IsEnabled | quote }}
        - name: RPIExecution__QueueListener__QueuePath
          value: {{ .Values.queueNames.listenerQueuePath | quote }}
        - name: RPIClient__ApplicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: Logging__Database__LogLevel__Default
          value: "Error"     
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir 
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: database-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: database-secrets
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-execution-service:{{ .Values.global.image_tag }}
        imagePullPolicy: Always
        name: execution-service
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-executionservice
            mountPath: /app/appsettings
          {{- if .Values.storage.enabled }}
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
          {{- end }}
      volumes:
        - name: rpi-executionservice
          configMap:
            name: rpi-executionservice
        {{- if .Values.storage.enabled }}
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: {{ .Values.storage.persistentVolumeClaim }}
        {{- end }}
{{- end }}

---

{{- if eq .Values.global.cloud "amazon" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-executionservice
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-executionservice
spec:
  replicas: {{ .Values.replicas.executionservice }}
  selector:
    matchLabels:
      app: rpi-executionservice
  template:
    metadata:
      labels:
        app: rpi-executionservice
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: sa-redpoint-rpi
      containers:
      - env:
        - name: RPI__SMTP__EmailSenderAddress
          value: {{ .Values.SMTPSettings.SMTP_SenderAddress | quote }}
        - name: RPI__SMTP__Address
          value: {{ .Values.SMTPSettings.SMTP_Address | quote }}
        - name: RPI__SMTP__Port
          value: {{ .Values.SMTPSettings.SMTP_Port | quote }}
        - name: RPI__SMTP__EnableSSL
          value: "true"
        - name: RPI__SMTP__UseCredentials
          value: "true"
        - name: RPI__SMTP__Username
          value: {{ .Values.SMTPSettings.SMTP_Username | quote }}
        - name: RPIExecution__QueueListener__IsEnabled
          value: {{ .Values.executionservice.RPIExecution__QueueListener__IsEnabled | quote }}
        - name: RPIExecution__QueueListener__QueuePath
          value: {{ .Values.queueNames.listenerQueuePath | quote }}
        - name: RPI__SMTP__Password
          value: {{ .Values.SMTPSettings.SMTP_Password | quote }}
        - name: RPIExecution__MaxThreadsPerExecutionService
          value: {{ .Values.executionservice.RPIExecution_MaxThreadsPerExecutionService | quote }}
        - name: RPIClient__ApplicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir
        - name: Logging__Database__LogLevel__Default
          value: "Error"     
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: database-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: database-secrets
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-execution-service:{{ .Values.global.image_tag }}
        imagePullPolicy: Always
        name: execution-service
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-executionservice
            mountPath: /app/appsettings
          {{- if .Values.storage.enabled }}
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
          {{- end }}
      volumes:
        - name: rpi-executionservice
          configMap:
            name: rpi-executionservice
        {{- if .Values.storage.enabled }}
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: {{ .Values.storage.persistentVolumeClaim }}
        {{- end }}
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

---
{{- if eq .Values.global.cloud "azure" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-executionservice
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-executionservice
spec:
  replicas: {{ .Values.replicas.executionservice }}
  selector:
    matchLabels:
      app: rpi-executionservice
  template:
    metadata:
      labels:
        app: rpi-executionservice
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: sa-redpoint-rpi
      containers:
      - env:
        - name: RPI__SMTP__EmailSenderAddress
          value: {{ .Values.SMTPSettings.SMTP_SenderAddress | quote }}
        - name: RPI__SMTP__Address
          value: {{ .Values.SMTPSettings.SMTP_Address | quote }}
        - name: RPI__SMTP__Port
          value: {{ .Values.SMTPSettings.SMTP_Port | quote }}
        - name: RPI__SMTP__EnableSSL
          value: "true"
        - name: RPI__SMTP__UseCredentials
          value: "true"
        - name: RPI__SMTP__Username
          value: {{ .Values.SMTPSettings.SMTP_Username | quote }}
        - name: RPI__SMTP__Password
          value: {{ .Values.SMTPSettings.SMTP_Password | quote }}
        - name: RPIExecution__QueueListener__IsEnabled
          value: {{ .Values.executionservice.RPIExecution__QueueListener__IsEnabled | quote }}
        - name: RPIExecution__QueueListener__QueuePath
          value: {{ .Values.queueNames.listenerQueuePath | quote }}
        - name: RPIExecution__MaxThreadsPerExecutionService
          value: {{ .Values.executionservice.RPIExecution_MaxThreadsPerExecutionService | quote }}
        - name: RPIClient__ApplicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir
        - name: Logging__Database__LogLevel__Default
          value: "Error"     
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: database-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: database-secrets
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-execution-service:{{ .Values.global.image_tag }}
        imagePullPolicy: Always
        name: execution-service
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-executionservice
            mountPath: /app/appsettings
          {{- if .Values.storage.enabled }}
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
          {{- end }}
      volumes:
        - name: rpi-executionservice
          configMap:
            name: rpi-executionservice
        {{- if .Values.storage.enabled }}
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: {{ .Values.storage.persistentVolumeClaim }}
        {{- end }}
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

---
{{- if eq .Values.global.cloud "google" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-executionservice
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-executionservice
spec:
  replicas: {{ .Values.replicas.executionservice }}
  selector:
    matchLabels:
      app: rpi-executionservice
  template:
    metadata:
      labels:
        app: rpi-executionservice
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: sa-redpoint-rpi
      containers:
      - env:
        - name: RPI__SMTP__EmailSenderAddress
          value: {{ .Values.SMTPSettings.SMTP_SenderAddress | quote }}
        - name: RPI__SMTP__Address
          value: {{ .Values.SMTPSettings.SMTP_Address | quote }}
        - name: RPI__SMTP__Port
          value: {{ .Values.SMTPSettings.SMTP_Port | quote }}
        - name: RPI__SMTP__EnableSSL
          value: "true"
        - name: RPI__SMTP__UseCredentials
          value: "true"
        - name: RPI__SMTP__Username
          value: {{ .Values.SMTPSettings.SMTP_Username | quote }}
        - name: RPI__SMTP__Password
          value: {{ .Values.SMTPSettings.SMTP_Password | quote }}
        - name: RPIExecution__QueueListener__IsEnabled
          value: {{ .Values.executionservice.RPIExecution__QueueListener__IsEnabled | quote }}
        - name: RPIExecution__QueueListener__QueuePath
          value: {{ .Values.queueNames.listenerQueuePath | quote }}
        - name: RPIExecution__MaxThreadsPerExecutionService
          value: {{ .Values.executionservice.RPIExecution_MaxThreadsPerExecutionService | quote }}
        - name: RPIClient__ApplicationSupportURL
          value: "https://support.redpointglobal.com"
        - name: Logging__LogLevel__Default
          value: "Error"
        - name: Logging__LogLevel__Microsoft
          value: "Error"
        - name: Logging__Database__RPITrace
          value: "Error"
        - name: RPI__FileOutput__Directory
          value: /rpifileoutputdir
        - name: Logging__Database__LogLevel__Default
          value: "Error"     
        - name: CONNECTIONSTRINGS__LOGGINGDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__LoggingDatabase
              name: database-secrets
        - name: CONNECTIONSTRINGS__OPERATIONALDATABASE
          valueFrom:
            secretKeyRef:
              key: ConnectionStrings__OperationalDatabase
              name: database-secrets
        image: rg1acrpub.azurecr.io/docker/redpointinteraction/prod/redpoint-interaction-execution-service:{{ .Values.global.image_tag }}
        imagePullPolicy: Always
        name: execution-service
        ports:
        - containerPort: 8080
          name: web-port
          protocol: TCP
        volumeMounts:
          - name: rpi-executionservice
            mountPath: /app/appsettings
          {{- if .Values.storage.enabled }}
          - name: rpifileoutputdir
            mountPath: /rpifileoutputdir
          {{- end }}
      volumes:
        - name: rpi-executionservice
          configMap:
            name: rpi-executionservice
        {{- if .Values.storage.enabled }}
        - name: rpifileoutputdir
          persistentVolumeClaim:
            claimName: {{ .Values.storage.persistentVolumeClaim }}
        {{- end }}
      {{- with .Values.global.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}