{{- if eq .Values.global.cloud "demo" }}
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: {{ .Values.global.namespace }}
data:
  ConnectionStrings__LoggingDatabase: {{ printf "Server=tcp:rpiopsmssqlserver,1433;Database=Pulse_Logging;User ID=sa;Password=.RedPoint2024;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" | b64enc }}
  ConnectionStrings__OperationalDatabase: {{ printf "Server=tcp:rpiopsmssqlserver,1433;Database=Pulse;User ID=sa;Password=.RedPoint2024;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" | b64enc }}
type: Opaque

{{- end }}

---
{{- if eq .Values.global.cloud "azure" }}
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: {{ .Values.global.namespace }}
data:
  ConnectionStrings__LoggingDatabase: {{ printf "Server=tcp:%s,1433;Database=%s;User ID=%s;Password=%s;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" .Values.databases.serverhost .Values.databases.loggingDatabaseName .Values.databases.username .Values.databases.password | b64enc }}
  ConnectionStrings__OperationalDatabase: {{ printf "Server=tcp:%s,1433;Database=%s;User ID=%s;Password=%s;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" .Values.databases.serverhost .Values.databases.operationsDatabaseName .Values.databases.username .Values.databases.password | b64enc }}
type: Opaque
{{- end }}

---
{{- if eq .Values.global.cloud "google" }}
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: {{ .Values.global.namespace }}
data:
  ConnectionStrings__LoggingDatabase: {{ printf "Server=tcp:%s,1433;Database=%s;User ID=%s;Password=%s;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" .Values.databases.serverhost .Values.databases.loggingDatabaseName .Values.databases.username .Values.databases.password | b64enc }}
  ConnectionStrings__OperationalDatabase: {{ printf "Server=tcp:%s,1433;Database=%s;User ID=%s;Password=%s;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" .Values.databases.serverhost .Values.databases.operationsDatabaseName .Values.databases.username .Values.databases.password | b64enc }}
type: Opaque
{{- end }}

---
{{- if eq .Values.global.cloud "amazon" }}
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: {{ .Values.global.namespace }}
data:
  ConnectionStrings__LoggingDatabase: {{ printf "Server=tcp:%s,1433;Database=%s;User ID=%s;Password=%s;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" .Values.databases.serverhost .Values.databases.loggingDatabaseName .Values.databases.username .Values.databases.password | b64enc }}
  ConnectionStrings__OperationalDatabase: {{ printf "Server=tcp:%s,1433;Database=%s;User ID=%s;Password=%s;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;" .Values.databases.serverhost .Values.databases.operationsDatabaseName .Values.databases.username .Values.databases.password | b64enc }}
type: Opaque
{{- end }}