{{- if $.Values.executionservice.autoscaling.enabled }}
{{- if eq $.Values.executionservice.autoscaling.type "hpa" }}
{{- if $.Values.executionservice.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-executionservice
  namespace: {{ $.Release.Namespace }}
  labels:
    app: rpi-executionservice
spec:
  scaleTargetRef:
    {{- if eq .Values.callbackapi.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-executionservice
    {{- end }}
    {{- if eq .Values.callbackapi.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rpi-executionservice
    {{- end }}
  minReplicas: {{ $.Values.executionservice.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.executionservice.autoscaling.maxReplicas }}
  metrics:
    {{- if $.Values.executionservice.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.executionservice.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $.Values.executionservice.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.executionservice.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.interactionapi.autoscaling.enabled }}
{{- if eq .Values.interactionapi.autoscaling.type "hpa" }}
{{- if .Values.interactionapi.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-interactionapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-interactionapi
spec:
  scaleTargetRef:
    {{- if eq .Values.interactionapi.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-interactionapi
    {{- end }}
    {{- if eq .Values.interactionapi.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rpi-interactionapi
    {{- end }}
  minReplicas: {{ .Values.interactionapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.interactionapi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.interactionapi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.interactionapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.interactionapi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.interactionapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.integrationapi.autoscaling.enabled }}
{{- if eq .Values.integrationapi.autoscaling.type "hpa" }}
{{- if .Values.integrationapi.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-integrationapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-integrationapi
spec:
  scaleTargetRef:
    {{- if eq .Values.integrationapi.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-integrationapi
    {{- end }}
    {{- if eq .Values.integrationapi.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rpi-integrationapi
    {{- end }}
  minReplicas: {{ .Values.integrationapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.integrationapi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.integrationapi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.integrationapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.integrationapi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.integrationapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.realtimeapi.autoscaling.enabled }}
{{- if eq .Values.realtimeapi.autoscaling.type "hpa" }}
{{- if .Values.realtimeapi.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-realtimeapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-realtimeapi
spec:
  scaleTargetRef:
    {{- if eq .Values.realtimeapi.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-realtimeapi
    {{- end }}
    {{- if eq .Values.realtimeapi.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rpi-realtimeapi
    {{- end }}
  minReplicas: {{ .Values.realtimeapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.realtimeapi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.realtimeapi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.realtimeapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.realtimeapi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.realtimeapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.callbackapi.autoscaling.enabled }}
{{- if eq .Values.callbackapi.autoscaling.type "hpa" }}
{{- if .Values.callbackapi.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-callbackapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-callbackapi
spec:
  scaleTargetRef:
    {{- if eq .Values.callbackapi.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-callbackapi
    {{- end }}
    {{- if eq .Values.callbackapi.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rpi-callbackapi
    {{- end }}
  minReplicas: {{ .Values.callbackapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.callbackapi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.callbackapi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.callbackapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.callbackapi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.callbackapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.queuereader.autoscaling.enabled }}
{{- if .Values.queuereader.enabled }}
{{- if eq .Values.queuereader.autoscaling.type "hpa" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-queuereader
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-queuereader
spec:
  scaleTargetRef:
    {{- if eq .Values.queuereader.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-queuereader
    {{- end }}
    {{- if eq .Values.queuereader.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rpi-queuereader
    {{- end }}
  minReplicas: {{ .Values.queuereader.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.queuereader.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.queuereader.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.queuereader.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.queuereader.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.queuereader.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.nodemanager.autoscaling.enabled }}
{{- if .Values.nodemanager.enabled }}
{{- if eq .Values.nodemanager.autoscaling.type "hpa" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-nodemanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-nodemanager
spec:
  scaleTargetRef:
    {{- if eq .Values.nodemanager.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-nodemanager
    {{- end }}
    {{- if eq .Values.nodemanager.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rpi-nodemanager
    {{- end }}
  minReplicas: {{ .Values.nodemanager.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nodemanager.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.nodemanager.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.nodemanager.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.nodemanager.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.nodemanager.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.smartActivation.enabled }}
{{- if .Values.socketio.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cdp-socketio
  namespace: {{ .Release.Namespace }}
  labels:
    app: cdp-socketio
spec:
  scaleTargetRef:
    {{- if eq .Values.socketio.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: cdp-socketio
    {{- end }}
    {{- if eq .Values.socketio.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: cdp-socketio
    {{- end }}
  minReplicas: {{ .Values.socketio.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.socketio.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.socketio.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.socketio.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.socketio.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.socketio.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.smartActivation.enabled }}
{{- if .Values.authservice.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cdp-authservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: cdp-authservice
spec:
  scaleTargetRef:
    {{- if eq .Values.authservice.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: cdp-authservice
    {{- end }}
    {{- if eq .Values.authservice.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: cdp-authservice
    {{- end }}
  minReplicas: {{ .Values.authservice.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.authservice.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.authservice.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.authservice.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.authservice.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.authservice.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.smartActivation.enabled }}
{{- if .Values.servicesapi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cdp-servicesapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: cdp-servicesapi
spec:
  scaleTargetRef:
    {{- if eq .Values.servicesapi.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: cdp-servicesapi
    {{- end }}
    {{- if eq .Values.servicesapi.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: cdp-servicesapi
    {{- end }}
  minReplicas: {{ .Values.servicesapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.servicesapi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.servicesapi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.servicesapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.servicesapi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.servicesapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.smartActivation.enabled }}
{{- if .Values.uiservice.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cdp-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: cdp-ui
spec:
  scaleTargetRef:
    {{- if eq .Values.uiservice.type "deployment" }}
    apiVersion: apps/v1
    kind: Deployment
    name: cdp-ui
    {{- end }}
    {{- if eq .Values.uiservice.type "rollout" }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: cdp-ui
    {{- end }}
  minReplicas: {{ .Values.uiservice.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.uiservice.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.uiservice.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.uiservice.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.uiservice.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.uiservice.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}