{{- if $.Values.executionservice.autoscaling.enabled }}
{{- if eq $.Values.executionservice.autoscaling.type "hpa" }}
{{- if $.Values.executionservice.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-executionservice
  namespace: {{ $.Release.Namespace }}
  labels:
    app: rpi-executionservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-executionservice
  minReplicas: {{ $.Values.executionservice.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.executionservice.autoscaling.maxReplicas }}
  metrics:
    {{- if $.Values.executionservice.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.executionservice.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $.Values.executionservice.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.executionservice.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.interactionapi.autoscaling.enabled }}
{{- if eq .Values.interactionapi.autoscaling.type "hpa" }}
{{- if .Values.interactionapi.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-interactionapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-interactionapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-interactionapi
  minReplicas: {{ .Values.interactionapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.interactionapi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.interactionapi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.interactionapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.interactionapi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.interactionapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.integrationapi.autoscaling.enabled }}
{{- if eq .Values.integrationapi.autoscaling.type "hpa" }}
{{- if .Values.integrationapi.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-integrationapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-integrationapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-integrationapi
  minReplicas: {{ .Values.integrationapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.integrationapi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.integrationapi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.integrationapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.integrationapi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.integrationapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.realtimeapi.autoscaling.enabled }}
{{- if eq .Values.realtimeapi.autoscaling.type "hpa" }}
{{- if .Values.realtimeapi.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-realtimeapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-realtimeapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-realtimeapi
  minReplicas: {{ .Values.realtimeapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.realtimeapi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.realtimeapi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.realtimeapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.realtimeapi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.realtimeapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.callbackapi.autoscaling.enabled }}
{{- if eq .Values.callbackapi.autoscaling.type "hpa" }}
{{- if .Values.callbackapi.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-callbackapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-callbackapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-callbackapi
  minReplicas: {{ .Values.callbackapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.callbackapi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.callbackapi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.callbackapi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.callbackapi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.callbackapi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.queuereader.autoscaling.enabled }}
{{- if .Values.queuereader.enabled }}
{{- if eq .Values.queuereader.autoscaling.type "hpa" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-queuereader
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-queuereader
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-queuereader
  minReplicas: {{ .Values.queuereader.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.queuereader.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.queuereader.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.queuereader.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.queuereader.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.queuereader.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}

---
{{- if .Values.nodemanager.autoscaling.enabled }}
{{- if .Values.nodemanager.enabled }}
{{- if eq .Values.nodemanager.autoscaling.type "hpa" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rpi-nodemanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: rpi-nodemanager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpi-nodemanager
  minReplicas: {{ .Values.nodemanager.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nodemanager.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.nodemanager.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.nodemanager.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.nodemanager.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.nodemanager.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}