apiVersion: v1
kind: Service
metadata:
  name: rpi-helpdocs
  namespace: {{ .Values.application.namespace }}
  labels:
    app: rpi-helpdocs
    env: {{ .Values.application.environment }}
    version: {{ .Values.application.version | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rpi-helpdocs

