apiVersion: v1
kind: Service
metadata:
  name: rpi-node-manager
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-node-manager
    env: {{ .Values.application.environment }}
    version: {{ .Values.application.version | quote }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rpi-node-manager

