{{- if eq .Values.global.cloud "amazon" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-nodemanager
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {
      "Authentication": {
        "EnableRPIAuthentication": true,
        {{- if .Values.OpenIdProviders.enabled }}
        "OpenIdProviders": [
          {
            "Name": {{ .Values.OpenIdProviders.Name | quote }},
            "AuthorizationHost": {{ .Values.OpenIdProviders.AuthorizationHost | quote }},
            "ClientID": {{ .Values.OpenIdProviders.ClientID | quote }},
            "Audience": {{ .Values.OpenIdProviders.Audience | quote }},
            "RedirectURL": {{ .Values.OpenIdProviders.RedirectURL | quote }},
            "EnableRefreshTokens": {{ .Values.OpenIdProviders.EnableRefreshTokens }},
            "ValidateIssuer": {{ .Values.OpenIdProviders.ValidateIssuer }},
            "ValidateAudience": {{ .Values.OpenIdProviders.ValidateAudience }},
            "LogoutIdTokenParameter": {{ .Values.OpenIdProviders.LogoutIdTokenParameter | quote }},
            "SupportsUserManagement": true,
            "CustomScopes": {{ .Values.OpenIdProviders.CustomScopes }}
          }
        ]
        {{- end }}
      },
      "DisableHttpRedirect": true
    }
{{- end }}

---
{{- if eq .Values.global.cloud "google" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-nodemanager
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {
      "Authentication": {
        "EnableRPIAuthentication": true,
        {{- if .Values.OpenIdProviders.enabled }}
        "OpenIdProviders": [
          {
            "Name": {{ .Values.OpenIdProviders.Name | quote }},
            "AuthorizationHost": {{ .Values.OpenIdProviders.AuthorizationHost | quote }},
            "ClientID": {{ .Values.OpenIdProviders.ClientID | quote }},
            "Audience": {{ .Values.OpenIdProviders.Audience | quote }},
            "RedirectURL": {{ .Values.OpenIdProviders.RedirectURL | quote }},
            "EnableRefreshTokens": {{ .Values.OpenIdProviders.EnableRefreshTokens }},
            "ValidateIssuer": {{ .Values.OpenIdProviders.ValidateIssuer }},
            "ValidateAudience": {{ .Values.OpenIdProviders.ValidateAudience }},
            "LogoutIdTokenParameter": {{ .Values.OpenIdProviders.LogoutIdTokenParameter | quote }},
            "SupportsUserManagement": true,
            "CustomScopes": {{ .Values.OpenIdProviders.CustomScopes }}
          }
        ]
        {{- end }}
      },
      "DisableHttpRedirect": true
    }
{{- end }}

---
{{- if eq .Values.global.cloud "azure" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-nodemanager
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {
      "Authentication": {
        "EnableRPIAuthentication": true,
        {{- if .Values.OpenIdProviders.enabled }}
        "OpenIdProviders": [
          {
            "Name": {{ .Values.OpenIdProviders.azure.Name | quote }},
            "AuthorizationHost": {{ .Values.OpenIdProviders.azure.AuthorizationHost | quote }},
            "ClientID": {{ .Values.OpenIdProviders.azure.ClientID | quote }},
            "Audience": {{ .Values.OpenIdProviders.azure.Audience | quote }},
            "RedirectURL": {{ .Values.OpenIdProviders.azure.RedirectURL | quote }},
            "EnableRefreshTokens": {{ .Values.OpenIdProviders.azure.EnableRefreshTokens }},
            "ValidateIssuer": {{ .Values.OpenIdProviders.azure.ValidateIssuer }},
            "ValidateAudience": {{ .Values.OpenIdProviders.azure.ValidateAudience }},
            "LogoutIdTokenParameter": {{ .Values.OpenIdProviders.azure.LogoutIdTokenParameter | quote }},
            "SupportsUserManagement": true,
            "CustomScopes": {{ .Values.OpenIdProviders.azure.CustomScopes }}
          }
        ]
        {{- end }}
      },
      "DisableHttpRedirect": true
    }
{{- end }}

---
{{- if eq .Values.global.cloud "demo" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi-nodemanager
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.overrides.json: |
    {
      "Authentication": {
        "EnableRPIAuthentication": true,
        {{- if .Values.OpenIdProviders.enabled }}
        "OpenIdProviders": [
          {
            "Name": {{ .Values.OpenIdProviders.Name | quote }},
            "AuthorizationHost": {{ .Values.OpenIdProviders.AuthorizationHost | quote }},
            "ClientID": {{ .Values.OpenIdProviders.ClientID | quote }},
            "Audience": {{ .Values.OpenIdProviders.Audience | quote }},
            "RedirectURL": {{ .Values.OpenIdProviders.RedirectURL | quote }},
            "EnableRefreshTokens": {{ .Values.OpenIdProviders.EnableRefreshTokens }},
            "ValidateIssuer": {{ .Values.OpenIdProviders.ValidateIssuer }},
            "ValidateAudience": {{ .Values.OpenIdProviders.ValidateAudience }},
            "LogoutIdTokenParameter": {{ .Values.OpenIdProviders.LogoutIdTokenParameter | quote }},
            "SupportsUserManagement": true,
            "CustomScopes": {{ .Values.OpenIdProviders.CustomScopes }}
          }
        ]
        {{- end }}
      },
      "DisableHttpRedirect": true
    }
{{- end }}