{{- if eq .Values.global.cloud "demo" }}
apiVersion: v1
kind: Service
metadata:
  name: rpi-rtcache-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-rtcache-redis
spec:
  ports:
  - name: http
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: rpi-rtcache-redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-rtcache-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rpi-rtcache-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpi-rtcache-redis
  template:
    metadata:
      labels:
        app: rpi-rtcache-redis
    spec:
      imagePullSecrets:
        - name: redpoint-rpi
      serviceAccountName: redpoint-rpi
      containers:
      - name: rpi-rtcache-redis
        image: rg1acrpub.azurecr.io/rpi/ancillary/rtcache/redis-6:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: web-port
          protocol: TCP
      hostname: rpi-rtcache-redis
{{- end }}