---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sql-rpi-ops
  namespace: {{ include "custom.namespace" . }}
  labels:
    app: sql-rpi-ops
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-rpi-ops
  namespace: {{ include "custom.namespace" . }}
  labels:
    app: sql-rpi-ops
spec:
  replicas: 1
  selector:
     matchLabels:
       app: sql-rpi-ops
  template:
    metadata:
      labels:
        app: sql-rpi-ops
    spec:
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: sql-rpi-ops
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: sql-rpi-ops
          mountPath: /var/opt/mssql
        resources:
          requests:
            cpu: 0.5
            memory: "512Mi"
          limits:
            cpu: 1
            memory: "1Gi"
      volumes:
      - name: sql-rpi-ops
        persistentVolumeClaim:
          claimName: sql-rpi-ops

---
apiVersion: v1
data:
  MSSQL_SA_PASSWORD: TXlDMG05bCZ4UEBzc3cwcmQ=
kind: Secret
metadata:
  name: mssql
  namespace: {{ include "custom.namespace" . }}
type: Opaque

---
apiVersion: v1
kind: Service
metadata:
  name: sql-rpi-ops
  namespace: {{ include "custom.namespace" . }}
spec:
  selector:
    app: sql-rpi-ops
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433

