apiVersion: v2
name: redpoint-rpi
description: A Helm chart for Redpoint Interaction (RPI)

dependencies:
  - name: mssql
    version: 0.1.0
    repository: "redpoint-rpi/charts/mssql"
    condition: mssql.enabled

type: application
version: 1.0.0
appVersion: "7.1"
